/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.flyaway.ncbroadblck.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredBlock;

import net.minecraft.world.level.block.Block;

import net.flyaway.ncbroadblck.block.*;
import net.flyaway.ncbroadblck.NcbRoadblckMod;

public class NcbRoadblckModBlocks {
	public static final DeferredRegister.Blocks REGISTRY = DeferredRegister.createBlocks(NcbRoadblckMod.MODID);
	public static final DeferredBlock<Block> ASPHALT_ROAD;
	public static final DeferredBlock<Block> ASPHALT_ROAD_SLAB;
	public static final DeferredBlock<Block> ASPHALT_ROAD_PLATE;
	public static final DeferredBlock<Block> ASPHALT_ROAD_SLOPE;
	public static final DeferredBlock<Block> ASPHALT_ROAD_SLOPE_PRO;
	public static final DeferredBlock<Block> ASPHALT_3_COLOR_LINE;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_LINK;
	public static final DeferredBlock<Block> ASPHALT_WHITE_WIDELINK;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_WIDELINK;
	public static final DeferredBlock<Block> ASPHALT_WHITE_LINK;
	public static final DeferredBlock<Block> ASPHALT_WHITE_LINE;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_2_LINE;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_LINE;
	public static final DeferredBlock<Block> ASPHALT_3_COLOR_LINE_SLAB;
	public static final DeferredBlock<Block> ASPHALT_WHITE_LINK_SLAB;
	public static final DeferredBlock<Block> ASPHALT_WHITE_WIDELINK_SLAB;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_LINK_SLAB;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_WIDELINK_SLAB;
	public static final DeferredBlock<Block> ASPHALT_WHITE_LINE_SLAB;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_LINE_SLAB;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_2_LINE_SLAB;
	public static final DeferredBlock<Block> ASPHALT_3_COLOR_LINE_SLOPE;
	public static final DeferredBlock<Block> ASPHALT_3_COLOR_LINE_SLOPE_PRO;
	public static final DeferredBlock<Block> ASPHALT_3_COLOR_LINE_PLATE;
	public static final DeferredBlock<Block> ASPHALT_WHITE_LINE_PLATE;
	public static final DeferredBlock<Block> ASPHALT_WHITE_LINE_SLOPE;
	public static final DeferredBlock<Block> ASPHALT_WHITE_LINE_SLOPE_PRO;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_2_LINE_PLATE;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_2_LINE_SLOPE;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_2_LINE_SLOPE_PRO;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_LINE_PLATE;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_LINE_SLOPE;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_LINE_SLOPE_PRO;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_GRIDLINE;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_GRIDLINE_SLAB;
	public static final DeferredBlock<Block> ASPHALT_WHITE_GRIDLINE;
	public static final DeferredBlock<Block> ASPHALT_WHITE_GRIDLINE_SLAB;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_FRAME;
	public static final DeferredBlock<Block> ASPHALT_WHITE_FRAME;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_FRAME_SLAB;
	public static final DeferredBlock<Block> ASPHALT_WHITE_FRAME_SLAB;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_SLASH;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_SLASH_SLAB;
	public static final DeferredBlock<Block> ASPHALT_WHITE_SLASH;
	public static final DeferredBlock<Block> ASPHALT_WHITE_SLASH_SLAB;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_BACKSLASH;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_BACKSLASH_SLAB;
	public static final DeferredBlock<Block> ASPHALT_WHITE_BACKSLASH;
	public static final DeferredBlock<Block> ASPHALT_WHITE_BACKSLASH_SLAB;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_LINESLASH;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_LINESLASH_SLAB;
	public static final DeferredBlock<Block> ASPHALT_WHITE_LINESLASH;
	public static final DeferredBlock<Block> ASPHALT_WHITE_LINESLASH_SLAB;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_2_LINESLASH;
	public static final DeferredBlock<Block> ASPHALT_YELLOW_2_LINESLASH_SLAB;
	public static final DeferredBlock<Block> ASPHALT_3_COLOR_LINESLASH;
	public static final DeferredBlock<Block> ASPHALT_3_COLOR_LINESLASH_SLAB;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_GRAY;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_GRAY_SLAB;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_GRAY_PLATE;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_GRAY_SLOPE;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_GRAY_SLOPE_PRO;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_GREEN;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_GREEN_SLAB;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_GREEN_PLATE;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_GREEN_SLOPE;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_GREEN_SLOPE_PRO;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_RED;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_RED_SLAB;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_RED_PLATE;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_RED_SLOPE;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_RED_SLOPE_PRO;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_YELLOW;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_YELLOW_SLAB;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_YELLOW_PLATE;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_YELLOW_SLOPE;
	public static final DeferredBlock<Block> PAVERS_CHECKERED_YELLOW_SLOPE_PRO;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_GRAY;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_GRAY_SLAB;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_GRAY_PLATE;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_GRAY_SLOPE;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_GRAY_SLOPE_PRO;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_GREEN;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_GREEN_SLAB;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_GREEN_PLATE;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_GREEN_SLOPE;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_GREEN_SLOPE_PRO;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_RED;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_RED_SLAB;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_RED_PLATE;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_RED_SLOPE;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_RED_SLOPE_PRO;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_YELLOW;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_YELLOW_SLAB;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_YELLOW_PLATE;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_YELLOW_SLOPE;
	public static final DeferredBlock<Block> PAVERS_INTERLOCK_YELLOW_SLOPE_PRO;
	public static final DeferredBlock<Block> PAVERS_SQUARE_GRAY;
	public static final DeferredBlock<Block> PAVERS_SQUARE_GRAY_SLAB;
	public static final DeferredBlock<Block> PAVERS_SQUARE_GRAY_PLATE;
	public static final DeferredBlock<Block> PAVERS_SQUARE_GRAY_SLOPE;
	public static final DeferredBlock<Block> PAVERS_SQUARE_GRAY_SLOPE_PRO;
	public static final DeferredBlock<Block> PAVERS_SQUARE_GREEN;
	public static final DeferredBlock<Block> PAVERS_SQUARE_GREEN_SLAB;
	public static final DeferredBlock<Block> PAVERS_SQUARE_GREEN_PLATE;
	public static final DeferredBlock<Block> PAVERS_SQUARE_GREEN_SLOPE;
	public static final DeferredBlock<Block> PAVERS_SQUARE_GREEN_SLOPE_PRO;
	public static final DeferredBlock<Block> PAVERS_SQUARE_RED;
	public static final DeferredBlock<Block> PAVERS_SQUARE_RED_SLAB;
	public static final DeferredBlock<Block> PAVERS_SQUARE_RED_PLATE;
	public static final DeferredBlock<Block> PAVERS_SQUARE_RED_SLOPE;
	public static final DeferredBlock<Block> PAVERS_SQUARE_RED_SLOPE_PRO;
	public static final DeferredBlock<Block> PAVERS_SQUARE_YELLOW;
	public static final DeferredBlock<Block> PAVERS_SQUARE_YELLOW_SLAB;
	public static final DeferredBlock<Block> PAVERS_SQUARE_YELLOW_PLATE;
	public static final DeferredBlock<Block> PAVERS_SQUARE_YELLOW_SLOPE;
	public static final DeferredBlock<Block> PAVERS_SQUARE_YELLOW_SLOPE_PRO;
	public static final DeferredBlock<Block> ASPHALT_TIDELINE;
	public static final DeferredBlock<Block> ASPHALT_TIDELINE_SLAB;
	public static final DeferredBlock<Block> ASPHALT_TIDELINE_L_SLAB;
	public static final DeferredBlock<Block> ASPHALT_TIDELINE_R_SLAB;
	public static final DeferredBlock<Block> ASPHALT_TIDELINE_L;
	public static final DeferredBlock<Block> ASPHALT_TIDELINE_R;
	public static final DeferredBlock<Block> ASPHALT_WHITE_WIDELINE;
	public static final DeferredBlock<Block> ASPHALT_WHITE_WIDELINE_SLAB;
	public static final DeferredBlock<Block> ASPHALT_SOLID_AND_DOTTED_LINE;
	public static final DeferredBlock<Block> ASPHALT_SOLID_AND_DOTTED_LINE_SLAB;
	public static final DeferredBlock<Block> ASPHALT_YIELD_LINE;
	public static final DeferredBlock<Block> ASPHALT_YIELD_LINE_SLAB;
	public static final DeferredBlock<Block> SHOULDER_ASPHALT;
	public static final DeferredBlock<Block> SHOULDER_ASPHALT_SLAB;
	public static final DeferredBlock<Block> SHOULDER_MARBLE;
	public static final DeferredBlock<Block> SHOULDER_MARBLE_SLAB;
	public static final DeferredBlock<Block> MARBLE;
	public static final DeferredBlock<Block> MARBLE_SLAB;
	public static final DeferredBlock<Block> CEMENT;
	public static final DeferredBlock<Block> CEMENT_SLAB;
	public static final DeferredBlock<Block> PATTERN_STEEL;
	public static final DeferredBlock<Block> PATTERN_STEEL_SLAB;
	public static final DeferredBlock<Block> SHOULDER_ASPHALT_L_SLOPE;
	public static final DeferredBlock<Block> SHOULDER_ASPHALT_R_SLOPE;
	public static final DeferredBlock<Block> SHOULDER_ASPHALT_L_SLOPE_PRO;
	public static final DeferredBlock<Block> SHOULDER_ASPHALT_R_SLOPE_PRO;
	public static final DeferredBlock<Block> SHOULDER_MARBLE_L_SLOPE;
	public static final DeferredBlock<Block> SHOULDER_MARBLE_R_SLOPE;
	public static final DeferredBlock<Block> SHOULDER_MARBLE_L_SLOPE_PRO;
	public static final DeferredBlock<Block> SHOULDER_MARBLE_R_SLOPE_PRO;
	public static final DeferredBlock<Block> SHOULDER_ASPHALT_SLASH;
	public static final DeferredBlock<Block> SHOULDER_ASPHALT_SLASH_SLAB;
	public static final DeferredBlock<Block> SHOULDER_MARBLE_SLASH;
	public static final DeferredBlock<Block> SHOULDER_MARBLE_SLASH_SLAB;
	public static final DeferredBlock<Block> SHOULDER_RAINGRATE;
	public static final DeferredBlock<Block> SHOULDER_RAINGRATE_SLAB;
	public static final DeferredBlock<Block> BOLLARD_SIDEWALK;
	public static final DeferredBlock<Block> STONE_PILLAR;
	public static final DeferredBlock<Block> SPEED_BUMP;
	public static final DeferredBlock<Block> GUARDRAIL;
	public static final DeferredBlock<Block> GUARDRAIL_SMALL;
	public static final DeferredBlock<Block> MARKING_LEFT;
	public static final DeferredBlock<Block> MARKING_LEFT_RIGHT;
	public static final DeferredBlock<Block> MARKING_LEFT_UTURN;
	public static final DeferredBlock<Block> MARKING_OFFSET_LEFT;
	public static final DeferredBlock<Block> MARKING_OFFSET_RIGHT;
	public static final DeferredBlock<Block> MARKING_RIGHT;
	public static final DeferredBlock<Block> MARKING_STRAIGHT;
	public static final DeferredBlock<Block> MARKING_STRAIGHT_LEFT;
	public static final DeferredBlock<Block> MARKING_STRAIGHT_RIGHT;
	public static final DeferredBlock<Block> MARKING_STRAIGHT_UTURN;
	public static final DeferredBlock<Block> MARKING_UTURN;
	public static final DeferredBlock<Block> BLIND_PATH_BAR;
	public static final DeferredBlock<Block> BLIND_PATH_BAR_SLAB;
	public static final DeferredBlock<Block> BLIND_PATH_DOT;
	public static final DeferredBlock<Block> BLIND_PATH_DOT_SLAB;
	public static final DeferredBlock<Block> BLIND_PATH_BAR_SLOPE;
	public static final DeferredBlock<Block> BLIND_PATH_BAR_SLOPE_PRO;
	public static final DeferredBlock<Block> BLIND_PATH_DOT_SLOPE;
	public static final DeferredBlock<Block> BLIND_PATH_DOT_SLOPE_PRO;
	public static final DeferredBlock<Block> MARKING_WATCH_FOR_PEDESTRIANS;
	public static final DeferredBlock<Block> MARKING_60_LOWSPEED;
	public static final DeferredBlock<Block> MARKING_80_LOWSPEED;
	public static final DeferredBlock<Block> MARKING_100_LOWSPEED;
	public static final DeferredBlock<Block> MARKING_40_LOWSPEED;
	public static final DeferredBlock<Block> MARKING_60_HIGHSPEED;
	public static final DeferredBlock<Block> MARKING_80_HIGHSPEED;
	public static final DeferredBlock<Block> MARKING_100_HIGHSPEED;
	public static final DeferredBlock<Block> MARKING_120_HIGHSPEED;
	public static final DeferredBlock<Block> TRAFFIC_SIGNAL_POLE;
	public static final DeferredBlock<Block> TRAFFIC_SIGNAL_MAST;
	public static final DeferredBlock<Block> ROADSIGN_STOP;
	public static final DeferredBlock<Block> TRAFFIC_SIGNAL_SMALLPOLE;
	public static final DeferredBlock<Block> ROADSIGN_YIELD;
	public static final DeferredBlock<Block> ROADSIGN_CROSSROADS;
	public static final DeferredBlock<Block> ROADSIGN_JUNCTION_LEFT;
	public static final DeferredBlock<Block> ROADSIGN_JUNCTION_RIGHT;
	public static final DeferredBlock<Block> ROADSIGN_JOINING_LEFT;
	public static final DeferredBlock<Block> ROADSIGN_JOINING_RIGHT;
	public static final DeferredBlock<Block> ROADSIGN_DIVERGING_LEFT;
	public static final DeferredBlock<Block> ROADSIGN_DIVERGING_RIGHT;
	public static final DeferredBlock<Block> ROADSIGN_ROUNDABOUT;
	public static final DeferredBlock<Block> ROADSIGN_TURN_LEFT;
	public static final DeferredBlock<Block> ROADSIGN_TURN_RIGHT;
	public static final DeferredBlock<Block> ROADSIGN_REVERSE_CURVE_LEFT;
	public static final DeferredBlock<Block> ROADSIGN_REVERSE_CURVE_RIGHT;
	public static final DeferredBlock<Block> ROADSIGN_WINDING_LEFT;
	public static final DeferredBlock<Block> ROADSIGN_WINDING_RIGHT;
	public static final DeferredBlock<Block> ROADSIGN_STEEP_ASCENT;
	public static final DeferredBlock<Block> ROADSIGN_STEEP_DESCENT;
	public static final DeferredBlock<Block> ROADSIGN_CONTINUOUS_DESCENT;
	public static final DeferredBlock<Block> ROADSIGN_NARROWS;
	public static final DeferredBlock<Block> ROADSIGN_NARROWS_LEFT;
	public static final DeferredBlock<Block> ROADSIGN_NARROWS_RIGHT;
	public static final DeferredBlock<Block> ROADSIGN_NARROW_BRIDGE;
	public static final DeferredBlock<Block> ROADSIGN_TWOWAY_TRAFFIC;
	public static final DeferredBlock<Block> ROADSIGN_PEDESTRIANS;
	public static final DeferredBlock<Block> ROADSIGN_CHILDREN;
	public static final DeferredBlock<Block> ROADSIGN_DISABLED_PERSONS;
	public static final DeferredBlock<Block> ROADSIGN_NONMOTORIZED_VEHICLES;
	public static final DeferredBlock<Block> ROADSIGN_TRAFFIC_SIGNALS;
	public static final DeferredBlock<Block> ROADSIGN_FALLINGROCKS_LEFT;
	public static final DeferredBlock<Block> ROADSIGN_FALLINGROCKS_RIGHT;
	public static final DeferredBlock<Block> ROADSIGN_MOUNTAIN_LEFT;
	public static final DeferredBlock<Block> ROADSIGN_MOUNTAIN_RIGHT;
	public static final DeferredBlock<Block> ROADSIGN_VILLAGE;
	public static final DeferredBlock<Block> ROADSIGN_TUNNEL;
	public static final DeferredBlock<Block> ROADSIGN_DANGERS;
	public static final DeferredBlock<Block> ROADSIGN_WORKS;
	public static final DeferredBlock<Block> ROADSIGN_Y_JUNCTION;
	public static final DeferredBlock<Block> ROADSIGN_T_JUNCTION;
	public static final DeferredBlock<Block> ROADSIGN_NO_ENTRY;
	public static final DeferredBlock<Block> ROADSIGN_NO_THOROUGHFARE;
	public static final DeferredBlock<Block> ROADSIGN_NO_LEFT_TURN;
	public static final DeferredBlock<Block> ROADSIGN_NO_LEFT_OR_RIGHT_TURN;
	public static final DeferredBlock<Block> ROADSIGN_NO_RIGHT_TURN;
	public static final DeferredBlock<Block> ROADSIGN_NO_STRAIGHT_AHEAD_OR_LEFT_TURN;
	public static final DeferredBlock<Block> ROADSIGN_NO_STRAIGHT_AHEAD;
	public static final DeferredBlock<Block> ROADSIGN_NO_STRAIGHT_AHEAD_OR_RIGHT_TURN;
	public static final DeferredBlock<Block> ROADSIGN_NO_UTURN;
	public static final DeferredBlock<Block> ROADSIGN_NO_ENTRY_FOR_ARTICULATED_VEHICLES;
	public static final DeferredBlock<Block> ROADSIGN_NO_ENTRY_FOR_BUSES;
	public static final DeferredBlock<Block> ROADSIGN_NO_ENTRY_FOR_MOTOR_VEHICLES;
	public static final DeferredBlock<Block> ROADSIGN_NO_ENTRY_FOR_MOTORCYCLES;
	public static final DeferredBlock<Block> ROADSIGN_NO_ENTRY_FOR_NON_MOTORIZED_VEHICLES;
	public static final DeferredBlock<Block> ROADSIGN_NO_ENTRY_FOR_PASSENGER_CARS;
	public static final DeferredBlock<Block> ROADSIGN_NO_ENTRY_FOR_PEDESTRIANS;
	public static final DeferredBlock<Block> ROADSIGN_NO_ENTRY_FOR_THREE_WHEELED_VEHICLES;
	public static final DeferredBlock<Block> ROADSIGN_NO_ENTRY_FOR_TRACTORS;
	public static final DeferredBlock<Block> ROADSIGN_NO_ENTRY_FOR_TRUCKS;
	public static final DeferredBlock<Block> ROADSIGN_NO_HONKING;
	public static final DeferredBlock<Block> ROADSIGN_STOP_FOR_INSPECTION;
	public static final DeferredBlock<Block> ROADSIGN_SPEED_LIMIT_5;
	public static final DeferredBlock<Block> ROADSIGN_SPEED_LIMIT_10;
	public static final DeferredBlock<Block> ROADSIGN_SPEED_LIMIT_15;
	public static final DeferredBlock<Block> ROADSIGN_SPEED_LIMIT_30;
	public static final DeferredBlock<Block> ROADSIGN_SPEED_LIMIT_40;
	public static final DeferredBlock<Block> ROADSIGN_SPEED_LIMIT_60;
	public static final DeferredBlock<Block> ROADSIGN_SPEED_LIMIT_80;
	public static final DeferredBlock<Block> ROADSIGN_SPEED_LIMIT_100;
	public static final DeferredBlock<Block> ROADSIGN_SPEED_LIMIT_120;
	public static final DeferredBlock<Block> ROADSIGN_NO_OVERTAKING;
	public static final DeferredBlock<Block> ROADSIGN_NO_PARKING;
	public static final DeferredBlock<Block> ROADSIGN_NO_WAITING;
	public static final DeferredBlock<Block> ROADSIGN_GIVE_WAY_TO_ONCOMING_VEHICLES;
	public static final DeferredBlock<Block> ROADSIGN_ONLY_TURN_LEFT;
	public static final DeferredBlock<Block> ROADSIGN_ONLY_TURN_LEFT_OR_RIGHT;
	public static final DeferredBlock<Block> ROADSIGN_ONLY_STRAIGHT_AHEAD_OR_TURN_LEFT;
	public static final DeferredBlock<Block> ROADSIGN_ONLY_STRAIGHT_AHEAD;
	public static final DeferredBlock<Block> ROADSIGN_ONLY_STRAIGHT_AHEAD_OR_TURN_RIGHT;
	public static final DeferredBlock<Block> ROADSIGN_KEEP_LEFT;
	public static final DeferredBlock<Block> ROADSIGN_KEEP_RIGHT;
	public static final DeferredBlock<Block> ROADSIGN_KEEP_ROUNDABOUT;
	public static final DeferredBlock<Block> ROADSIGN_ONLY_MOTOR_VEHICLES;
	public static final DeferredBlock<Block> ROADSIGN_ONLY_NON_MOTORIZED_VEHICLES;
	public static final DeferredBlock<Block> ROADSIGN_ONLY_PEDESTRIANS;
	public static final DeferredBlock<Block> ROADSIGN_SOUND_HORN;
	public static final DeferredBlock<Block> ROADSIGN_SWITCH_ON_LIGHTS;
	public static final DeferredBlock<Block> ROADSIGN_MINIMUM_SPEED_LIMIT_40;
	public static final DeferredBlock<Block> ROADSIGN_MINIMUM_SPEED_LIMIT_60;
	public static final DeferredBlock<Block> ROADSIGN_MINIMUM_SPEED_LIMIT_80;
	public static final DeferredBlock<Block> ROADSIGN_MINIMUM_SPEED_LIMIT_100;
	public static final DeferredBlock<Block> ROADSIGN_ONLY_TURN_RIGHT;
	public static final DeferredBlock<Block> ROADSIGN_PARKING;
	public static final DeferredBlock<Block> ROADSIGN_PARKING_LEFT;
	public static final DeferredBlock<Block> ROADSIGN_PARKING_RIGHT;
	public static final DeferredBlock<Block> ROADSIGN_PARKING_RESERVED;
	public static final DeferredBlock<Block> ROADSIGN_PARKING_FOR_BUSES;
	public static final DeferredBlock<Block> ROADSIGN_PARKING_FOR_SCHOOL_BUSES;
	public static final DeferredBlock<Block> ROADSIGN_PARKING_FOR_TAXIS;
	public static final DeferredBlock<Block> ROADSIGN_PARKING_FOR_EV_CHARGING;
	public static final DeferredBlock<Block> ROADSIGN_PARKING_FOR_NON_MOTORIZED_VEHICLES;
	public static final DeferredBlock<Block> ROADSIGN_PARKING_FOR_DISABLED_PERSONS;
	public static final DeferredBlock<Block> ROADSIGN_PEDESTRIAN_CROSSING;
	public static final DeferredBlock<Block> ROADSIGN_UTURN;
	public static final DeferredBlock<Block> ROADSIGN_PRIORITY_OVER_ONCOMING_VEHICLES;
	public static final DeferredBlock<Block> ROADSIGN_HARD_SHOULDER_AVAILABLE_FOR_TRAFFIC;
	public static final DeferredBlock<Block> ROADSIGN_HARD_SHOULDER_AVAILABLE_END;
	public static final DeferredBlock<Block> ROADSIGN_HARD_SHOULDER_AVAILABLE_CLOSE;
	public static final DeferredBlock<Block> ROADSIGN_END_OF_NO_OVERTAKING;
	public static final DeferredBlock<Block> ROADSIGN_END_OF_SPEED_LIMIT_30;
	public static final DeferredBlock<Block> ROADSIGN_END_OF_SPEED_LIMIT_40;
	public static final DeferredBlock<Block> ROADSIGN_END_OF_SPEED_LIMIT_60;
	public static final DeferredBlock<Block> ROADSIGN_END_OF_SPEED_LIMIT_80;
	public static final DeferredBlock<Block> ROADSIGN_END_OF_SPEED_LIMIT_100;
	static {
		ASPHALT_ROAD = REGISTRY.register("asphalt_road", AsphaltRoadBlock::new);
		ASPHALT_ROAD_SLAB = REGISTRY.register("asphalt_road_slab", AsphaltRoadSlabBlock::new);
		ASPHALT_ROAD_PLATE = REGISTRY.register("asphalt_road_plate", AsphaltRoadPlateBlock::new);
		ASPHALT_ROAD_SLOPE = REGISTRY.register("asphalt_road_slope", AsphaltRoadSlopeBlock::new);
		ASPHALT_ROAD_SLOPE_PRO = REGISTRY.register("asphalt_road_slope_pro", AsphaltRoadSlopeProBlock::new);
		ASPHALT_3_COLOR_LINE = REGISTRY.register("asphalt_3_color_line", Asphalt3ColorLineBlock::new);
		ASPHALT_YELLOW_LINK = REGISTRY.register("asphalt_yellow_link", AsphaltYellowLinkBlock::new);
		ASPHALT_WHITE_WIDELINK = REGISTRY.register("asphalt_white_widelink", AsphaltWhiteWidelinkBlock::new);
		ASPHALT_YELLOW_WIDELINK = REGISTRY.register("asphalt_yellow_widelink", AsphaltYellowWidelinkBlock::new);
		ASPHALT_WHITE_LINK = REGISTRY.register("asphalt_white_link", AsphaltWhiteLinkBlock::new);
		ASPHALT_WHITE_LINE = REGISTRY.register("asphalt_white_line", AsphaltWhiteLineBlock::new);
		ASPHALT_YELLOW_2_LINE = REGISTRY.register("asphalt_yellow_2_line", AsphaltYellow2LineBlock::new);
		ASPHALT_YELLOW_LINE = REGISTRY.register("asphalt_yellow_line", AsphaltYellowLineBlock::new);
		ASPHALT_3_COLOR_LINE_SLAB = REGISTRY.register("asphalt_3_color_line_slab", Asphalt3ColorLineSlabBlock::new);
		ASPHALT_WHITE_LINK_SLAB = REGISTRY.register("asphalt_white_link_slab", AsphaltWhiteLinkSlabBlock::new);
		ASPHALT_WHITE_WIDELINK_SLAB = REGISTRY.register("asphalt_white_widelink_slab", AsphaltWhiteWidelinkSlabBlock::new);
		ASPHALT_YELLOW_LINK_SLAB = REGISTRY.register("asphalt_yellow_link_slab", AsphaltYellowLinkSlabBlock::new);
		ASPHALT_YELLOW_WIDELINK_SLAB = REGISTRY.register("asphalt_yellow_widelink_slab", AsphaltYellowWidelinkSlabBlock::new);
		ASPHALT_WHITE_LINE_SLAB = REGISTRY.register("asphalt_white_line_slab", AsphaltWhiteLineSlabBlock::new);
		ASPHALT_YELLOW_LINE_SLAB = REGISTRY.register("asphalt_yellow_line_slab", AsphaltYellowLineSlabBlock::new);
		ASPHALT_YELLOW_2_LINE_SLAB = REGISTRY.register("asphalt_yellow_2_line_slab", AsphaltYellow2LineSlabBlock::new);
		ASPHALT_3_COLOR_LINE_SLOPE = REGISTRY.register("asphalt_3_color_line_slope", Asphalt3ColorLineSlopeBlock::new);
		ASPHALT_3_COLOR_LINE_SLOPE_PRO = REGISTRY.register("asphalt_3_color_line_slope_pro", Asphalt3ColorLineSlopeProBlock::new);
		ASPHALT_3_COLOR_LINE_PLATE = REGISTRY.register("asphalt_3_color_line_plate", Asphalt3ColorLinePlateBlock::new);
		ASPHALT_WHITE_LINE_PLATE = REGISTRY.register("asphalt_white_line_plate", AsphaltWhiteLinePlateBlock::new);
		ASPHALT_WHITE_LINE_SLOPE = REGISTRY.register("asphalt_white_line_slope", AsphaltWhiteLineSlopeBlock::new);
		ASPHALT_WHITE_LINE_SLOPE_PRO = REGISTRY.register("asphalt_white_line_slope_pro", AsphaltWhiteLineSlopeProBlock::new);
		ASPHALT_YELLOW_2_LINE_PLATE = REGISTRY.register("asphalt_yellow_2_line_plate", AsphaltYellow2LinePlateBlock::new);
		ASPHALT_YELLOW_2_LINE_SLOPE = REGISTRY.register("asphalt_yellow_2_line_slope", AsphaltYellow2LineSlopeBlock::new);
		ASPHALT_YELLOW_2_LINE_SLOPE_PRO = REGISTRY.register("asphalt_yellow_2_line_slope_pro", AsphaltYellow2LineSlopeProBlock::new);
		ASPHALT_YELLOW_LINE_PLATE = REGISTRY.register("asphalt_yellow_line_plate", AsphaltYellowLinePlateBlock::new);
		ASPHALT_YELLOW_LINE_SLOPE = REGISTRY.register("asphalt_yellow_line_slope", AsphaltYellowLineSlopeBlock::new);
		ASPHALT_YELLOW_LINE_SLOPE_PRO = REGISTRY.register("asphalt_yellow_line_slope_pro", AsphaltYellowLineSlopeProBlock::new);
		ASPHALT_YELLOW_GRIDLINE = REGISTRY.register("asphalt_yellow_gridline", AsphaltYellowGridlineBlock::new);
		ASPHALT_YELLOW_GRIDLINE_SLAB = REGISTRY.register("asphalt_yellow_gridline_slab", AsphaltYellowGridlineSlabBlock::new);
		ASPHALT_WHITE_GRIDLINE = REGISTRY.register("asphalt_white_gridline", AsphaltWhiteGridlineBlock::new);
		ASPHALT_WHITE_GRIDLINE_SLAB = REGISTRY.register("asphalt_white_gridline_slab", AsphaltWhiteGridlineSlabBlock::new);
		ASPHALT_YELLOW_FRAME = REGISTRY.register("asphalt_yellow_frame", AsphaltYellowFrameBlock::new);
		ASPHALT_WHITE_FRAME = REGISTRY.register("asphalt_white_frame", AsphaltWhiteFrameBlock::new);
		ASPHALT_YELLOW_FRAME_SLAB = REGISTRY.register("asphalt_yellow_frame_slab", AsphaltYellowFrameSlabBlock::new);
		ASPHALT_WHITE_FRAME_SLAB = REGISTRY.register("asphalt_white_frame_slab", AsphaltWhiteFrameSlabBlock::new);
		ASPHALT_YELLOW_SLASH = REGISTRY.register("asphalt_yellow_slash", AsphaltYellowSlashBlock::new);
		ASPHALT_YELLOW_SLASH_SLAB = REGISTRY.register("asphalt_yellow_slash_slab", AsphaltYellowSlashSlabBlock::new);
		ASPHALT_WHITE_SLASH = REGISTRY.register("asphalt_white_slash", AsphaltWhiteSlashBlock::new);
		ASPHALT_WHITE_SLASH_SLAB = REGISTRY.register("asphalt_white_slash_slab", AsphaltWhiteSlashSlabBlock::new);
		ASPHALT_YELLOW_BACKSLASH = REGISTRY.register("asphalt_yellow_backslash", AsphaltYellowBackslashBlock::new);
		ASPHALT_YELLOW_BACKSLASH_SLAB = REGISTRY.register("asphalt_yellow_backslash_slab", AsphaltYellowBackslashSlabBlock::new);
		ASPHALT_WHITE_BACKSLASH = REGISTRY.register("asphalt_white_backslash", AsphaltWhiteBackslashBlock::new);
		ASPHALT_WHITE_BACKSLASH_SLAB = REGISTRY.register("asphalt_white_backslash_slab", AsphaltWhiteBackslashSlabBlock::new);
		ASPHALT_YELLOW_LINESLASH = REGISTRY.register("asphalt_yellow_lineslash", AsphaltYellowLineslashBlock::new);
		ASPHALT_YELLOW_LINESLASH_SLAB = REGISTRY.register("asphalt_yellow_lineslash_slab", AsphaltYellowLineslashSlabBlock::new);
		ASPHALT_WHITE_LINESLASH = REGISTRY.register("asphalt_white_lineslash", AsphaltWhiteLineslashBlock::new);
		ASPHALT_WHITE_LINESLASH_SLAB = REGISTRY.register("asphalt_white_lineslash_slab", AsphaltWhiteLineslashSlabBlock::new);
		ASPHALT_YELLOW_2_LINESLASH = REGISTRY.register("asphalt_yellow_2_lineslash", AsphaltYellow2LineslashBlock::new);
		ASPHALT_YELLOW_2_LINESLASH_SLAB = REGISTRY.register("asphalt_yellow_2_lineslash_slab", AsphaltYellow2LineslashSlabBlock::new);
		ASPHALT_3_COLOR_LINESLASH = REGISTRY.register("asphalt_3_color_lineslash", Asphalt3ColorLineslashBlock::new);
		ASPHALT_3_COLOR_LINESLASH_SLAB = REGISTRY.register("asphalt_3_color_lineslash_slab", Asphalt3ColorLineslashSlabBlock::new);
		PAVERS_CHECKERED_GRAY = REGISTRY.register("pavers_checkered_gray", PaversCheckeredGrayBlock::new);
		PAVERS_CHECKERED_GRAY_SLAB = REGISTRY.register("pavers_checkered_gray_slab", PaversCheckeredGraySlabBlock::new);
		PAVERS_CHECKERED_GRAY_PLATE = REGISTRY.register("pavers_checkered_gray_plate", PaversCheckeredGrayPlateBlock::new);
		PAVERS_CHECKERED_GRAY_SLOPE = REGISTRY.register("pavers_checkered_gray_slope", PaversCheckeredGraySlopeBlock::new);
		PAVERS_CHECKERED_GRAY_SLOPE_PRO = REGISTRY.register("pavers_checkered_gray_slope_pro", PaversCheckeredGraySlopeProBlock::new);
		PAVERS_CHECKERED_GREEN = REGISTRY.register("pavers_checkered_green", PaversCheckeredGreenBlock::new);
		PAVERS_CHECKERED_GREEN_SLAB = REGISTRY.register("pavers_checkered_green_slab", PaversCheckeredGreenSlabBlock::new);
		PAVERS_CHECKERED_GREEN_PLATE = REGISTRY.register("pavers_checkered_green_plate", PaversCheckeredGreenPlateBlock::new);
		PAVERS_CHECKERED_GREEN_SLOPE = REGISTRY.register("pavers_checkered_green_slope", PaversCheckeredGreenSlopeBlock::new);
		PAVERS_CHECKERED_GREEN_SLOPE_PRO = REGISTRY.register("pavers_checkered_green_slope_pro", PaversCheckeredGreenSlopeProBlock::new);
		PAVERS_CHECKERED_RED = REGISTRY.register("pavers_checkered_red", PaversCheckeredRedBlock::new);
		PAVERS_CHECKERED_RED_SLAB = REGISTRY.register("pavers_checkered_red_slab", PaversCheckeredRedSlabBlock::new);
		PAVERS_CHECKERED_RED_PLATE = REGISTRY.register("pavers_checkered_red_plate", PaversCheckeredRedPlateBlock::new);
		PAVERS_CHECKERED_RED_SLOPE = REGISTRY.register("pavers_checkered_red_slope", PaversCheckeredRedSlopeBlock::new);
		PAVERS_CHECKERED_RED_SLOPE_PRO = REGISTRY.register("pavers_checkered_red_slope_pro", PaversCheckeredRedSlopeProBlock::new);
		PAVERS_CHECKERED_YELLOW = REGISTRY.register("pavers_checkered_yellow", PaversCheckeredYellowBlock::new);
		PAVERS_CHECKERED_YELLOW_SLAB = REGISTRY.register("pavers_checkered_yellow_slab", PaversCheckeredYellowSlabBlock::new);
		PAVERS_CHECKERED_YELLOW_PLATE = REGISTRY.register("pavers_checkered_yellow_plate", PaversCheckeredYellowPlateBlock::new);
		PAVERS_CHECKERED_YELLOW_SLOPE = REGISTRY.register("pavers_checkered_yellow_slope", PaversCheckeredYellowSlopeBlock::new);
		PAVERS_CHECKERED_YELLOW_SLOPE_PRO = REGISTRY.register("pavers_checkered_yellow_slope_pro", PaversCheckeredYellowSlopeProBlock::new);
		PAVERS_INTERLOCK_GRAY = REGISTRY.register("pavers_interlock_gray", PaversInterlockGrayBlock::new);
		PAVERS_INTERLOCK_GRAY_SLAB = REGISTRY.register("pavers_interlock_gray_slab", PaversInterlockGraySlabBlock::new);
		PAVERS_INTERLOCK_GRAY_PLATE = REGISTRY.register("pavers_interlock_gray_plate", PaversInterlockGrayPlateBlock::new);
		PAVERS_INTERLOCK_GRAY_SLOPE = REGISTRY.register("pavers_interlock_gray_slope", PaversInterlockGraySlopeBlock::new);
		PAVERS_INTERLOCK_GRAY_SLOPE_PRO = REGISTRY.register("pavers_interlock_gray_slope_pro", PaversInterlockGraySlopeProBlock::new);
		PAVERS_INTERLOCK_GREEN = REGISTRY.register("pavers_interlock_green", PaversInterlockGreenBlock::new);
		PAVERS_INTERLOCK_GREEN_SLAB = REGISTRY.register("pavers_interlock_green_slab", PaversInterlockGreenSlabBlock::new);
		PAVERS_INTERLOCK_GREEN_PLATE = REGISTRY.register("pavers_interlock_green_plate", PaversInterlockGreenPlateBlock::new);
		PAVERS_INTERLOCK_GREEN_SLOPE = REGISTRY.register("pavers_interlock_green_slope", PaversInterlockGreenSlopeBlock::new);
		PAVERS_INTERLOCK_GREEN_SLOPE_PRO = REGISTRY.register("pavers_interlock_green_slope_pro", PaversInterlockGreenSlopeProBlock::new);
		PAVERS_INTERLOCK_RED = REGISTRY.register("pavers_interlock_red", PaversInterlockRedBlock::new);
		PAVERS_INTERLOCK_RED_SLAB = REGISTRY.register("pavers_interlock_red_slab", PaversInterlockRedSlabBlock::new);
		PAVERS_INTERLOCK_RED_PLATE = REGISTRY.register("pavers_interlock_red_plate", PaversInterlockRedPlateBlock::new);
		PAVERS_INTERLOCK_RED_SLOPE = REGISTRY.register("pavers_interlock_red_slope", PaversInterlockRedSlopeBlock::new);
		PAVERS_INTERLOCK_RED_SLOPE_PRO = REGISTRY.register("pavers_interlock_red_slope_pro", PaversInterlockRedSlopeProBlock::new);
		PAVERS_INTERLOCK_YELLOW = REGISTRY.register("pavers_interlock_yellow", PaversInterlockYellowBlock::new);
		PAVERS_INTERLOCK_YELLOW_SLAB = REGISTRY.register("pavers_interlock_yellow_slab", PaversInterlockYellowSlabBlock::new);
		PAVERS_INTERLOCK_YELLOW_PLATE = REGISTRY.register("pavers_interlock_yellow_plate", PaversInterlockYellowPlateBlock::new);
		PAVERS_INTERLOCK_YELLOW_SLOPE = REGISTRY.register("pavers_interlock_yellow_slope", PaversInterlockYellowSlopeBlock::new);
		PAVERS_INTERLOCK_YELLOW_SLOPE_PRO = REGISTRY.register("pavers_interlock_yellow_slope_pro", PaversInterlockYellowSlopeProBlock::new);
		PAVERS_SQUARE_GRAY = REGISTRY.register("pavers_square_gray", PaversSquareGrayBlock::new);
		PAVERS_SQUARE_GRAY_SLAB = REGISTRY.register("pavers_square_gray_slab", PaversSquareGraySlabBlock::new);
		PAVERS_SQUARE_GRAY_PLATE = REGISTRY.register("pavers_square_gray_plate", PaversSquareGrayPlateBlock::new);
		PAVERS_SQUARE_GRAY_SLOPE = REGISTRY.register("pavers_square_gray_slope", PaversSquareGraySlopeBlock::new);
		PAVERS_SQUARE_GRAY_SLOPE_PRO = REGISTRY.register("pavers_square_gray_slope_pro", PaversSquareGraySlopeProBlock::new);
		PAVERS_SQUARE_GREEN = REGISTRY.register("pavers_square_green", PaversSquareGreenBlock::new);
		PAVERS_SQUARE_GREEN_SLAB = REGISTRY.register("pavers_square_green_slab", PaversSquareGreenSlabBlock::new);
		PAVERS_SQUARE_GREEN_PLATE = REGISTRY.register("pavers_square_green_plate", PaversSquareGreenPlateBlock::new);
		PAVERS_SQUARE_GREEN_SLOPE = REGISTRY.register("pavers_square_green_slope", PaversSquareGreenSlopeBlock::new);
		PAVERS_SQUARE_GREEN_SLOPE_PRO = REGISTRY.register("pavers_square_green_slope_pro", PaversSquareGreenSlopeProBlock::new);
		PAVERS_SQUARE_RED = REGISTRY.register("pavers_square_red", PaversSquareRedBlock::new);
		PAVERS_SQUARE_RED_SLAB = REGISTRY.register("pavers_square_red_slab", PaversSquareRedSlabBlock::new);
		PAVERS_SQUARE_RED_PLATE = REGISTRY.register("pavers_square_red_plate", PaversSquareRedPlateBlock::new);
		PAVERS_SQUARE_RED_SLOPE = REGISTRY.register("pavers_square_red_slope", PaversSquareRedSlopeBlock::new);
		PAVERS_SQUARE_RED_SLOPE_PRO = REGISTRY.register("pavers_square_red_slope_pro", PaversSquareRedSlopeProBlock::new);
		PAVERS_SQUARE_YELLOW = REGISTRY.register("pavers_square_yellow", PaversSquareYellowBlock::new);
		PAVERS_SQUARE_YELLOW_SLAB = REGISTRY.register("pavers_square_yellow_slab", PaversSquareYellowSlabBlock::new);
		PAVERS_SQUARE_YELLOW_PLATE = REGISTRY.register("pavers_square_yellow_plate", PaversSquareYellowPlateBlock::new);
		PAVERS_SQUARE_YELLOW_SLOPE = REGISTRY.register("pavers_square_yellow_slope", PaversSquareYellowSlopeBlock::new);
		PAVERS_SQUARE_YELLOW_SLOPE_PRO = REGISTRY.register("pavers_square_yellow_slope_pro", PaversSquareYellowSlopeProBlock::new);
		ASPHALT_TIDELINE = REGISTRY.register("asphalt_tideline", AsphaltTidelineBlock::new);
		ASPHALT_TIDELINE_SLAB = REGISTRY.register("asphalt_tideline_slab", AsphaltTidelineSlabBlock::new);
		ASPHALT_TIDELINE_L_SLAB = REGISTRY.register("asphalt_tideline_l_slab", AsphaltTidelineLSlabBlock::new);
		ASPHALT_TIDELINE_R_SLAB = REGISTRY.register("asphalt_tideline_r_slab", AsphaltTidelineRSlabBlock::new);
		ASPHALT_TIDELINE_L = REGISTRY.register("asphalt_tideline_l", AsphaltTidelineLBlock::new);
		ASPHALT_TIDELINE_R = REGISTRY.register("asphalt_tideline_r", AsphaltTidelineRBlock::new);
		ASPHALT_WHITE_WIDELINE = REGISTRY.register("asphalt_white_wideline", AsphaltWhiteWidelineBlock::new);
		ASPHALT_WHITE_WIDELINE_SLAB = REGISTRY.register("asphalt_white_wideline_slab", AsphaltWhiteWidelineSlabBlock::new);
		ASPHALT_SOLID_AND_DOTTED_LINE = REGISTRY.register("asphalt_solid_and_dotted_line", AsphaltSolidAndDottedLineBlock::new);
		ASPHALT_SOLID_AND_DOTTED_LINE_SLAB = REGISTRY.register("asphalt_solid_and_dotted_line_slab", AsphaltSolidAndDottedLineSlabBlock::new);
		ASPHALT_YIELD_LINE = REGISTRY.register("asphalt_yield_line", AsphaltYieldLineBlock::new);
		ASPHALT_YIELD_LINE_SLAB = REGISTRY.register("asphalt_yield_line_slab", AsphaltYieldLineSlabBlock::new);
		SHOULDER_ASPHALT = REGISTRY.register("shoulder_asphalt", ShoulderAsphaltBlock::new);
		SHOULDER_ASPHALT_SLAB = REGISTRY.register("shoulder_asphalt_slab", ShoulderAsphaltSlabBlock::new);
		SHOULDER_MARBLE = REGISTRY.register("shoulder_marble", ShoulderMarbleBlock::new);
		SHOULDER_MARBLE_SLAB = REGISTRY.register("shoulder_marble_slab", ShoulderMarbleSlabBlock::new);
		MARBLE = REGISTRY.register("marble", MarbleBlock::new);
		MARBLE_SLAB = REGISTRY.register("marble_slab", MarbleSlabBlock::new);
		CEMENT = REGISTRY.register("cement", CementBlock::new);
		CEMENT_SLAB = REGISTRY.register("cement_slab", CementSlabBlock::new);
		PATTERN_STEEL = REGISTRY.register("pattern_steel", PatternSteelBlock::new);
		PATTERN_STEEL_SLAB = REGISTRY.register("pattern_steel_slab", PatternSteelSlabBlock::new);
		SHOULDER_ASPHALT_L_SLOPE = REGISTRY.register("shoulder_asphalt_l_slope", ShoulderAsphaltLSlopeBlock::new);
		SHOULDER_ASPHALT_R_SLOPE = REGISTRY.register("shoulder_asphalt_r_slope", ShoulderAsphaltRSlopeBlock::new);
		SHOULDER_ASPHALT_L_SLOPE_PRO = REGISTRY.register("shoulder_asphalt_l_slope_pro", ShoulderAsphaltLSlopeProBlock::new);
		SHOULDER_ASPHALT_R_SLOPE_PRO = REGISTRY.register("shoulder_asphalt_r_slope_pro", ShoulderAsphaltRSlopeProBlock::new);
		SHOULDER_MARBLE_L_SLOPE = REGISTRY.register("shoulder_marble_l_slope", ShoulderMarbleLSlopeBlock::new);
		SHOULDER_MARBLE_R_SLOPE = REGISTRY.register("shoulder_marble_r_slope", ShoulderMarbleRSlopeBlock::new);
		SHOULDER_MARBLE_L_SLOPE_PRO = REGISTRY.register("shoulder_marble_l_slope_pro", ShoulderMarbleLSlopeProBlock::new);
		SHOULDER_MARBLE_R_SLOPE_PRO = REGISTRY.register("shoulder_marble_r_slope_pro", ShoulderMarbleRSlopeProBlock::new);
		SHOULDER_ASPHALT_SLASH = REGISTRY.register("shoulder_asphalt_slash", ShoulderAsphaltSlashBlock::new);
		SHOULDER_ASPHALT_SLASH_SLAB = REGISTRY.register("shoulder_asphalt_slash_slab", ShoulderAsphaltSlashSlabBlock::new);
		SHOULDER_MARBLE_SLASH = REGISTRY.register("shoulder_marble_slash", ShoulderMarbleSlashBlock::new);
		SHOULDER_MARBLE_SLASH_SLAB = REGISTRY.register("shoulder_marble_slash_slab", ShoulderMarbleSlashSlabBlock::new);
		SHOULDER_RAINGRATE = REGISTRY.register("shoulder_raingrate", ShoulderRaingrateBlock::new);
		SHOULDER_RAINGRATE_SLAB = REGISTRY.register("shoulder_raingrate_slab", ShoulderRaingrateSlabBlock::new);
		BOLLARD_SIDEWALK = REGISTRY.register("bollard_sidewalk", BollardSidewalkBlock::new);
		STONE_PILLAR = REGISTRY.register("stone_pillar", StonePillarBlock::new);
		SPEED_BUMP = REGISTRY.register("speed_bump", SpeedBumpBlock::new);
		GUARDRAIL = REGISTRY.register("guardrail", GuardrailBlock::new);
		GUARDRAIL_SMALL = REGISTRY.register("guardrail_small", GuardrailSmallBlock::new);
		MARKING_LEFT = REGISTRY.register("marking_left", MarkingLeftBlock::new);
		MARKING_LEFT_RIGHT = REGISTRY.register("marking_left_right", MarkingLeftRightBlock::new);
		MARKING_LEFT_UTURN = REGISTRY.register("marking_left_uturn", MarkingLeftUturnBlock::new);
		MARKING_OFFSET_LEFT = REGISTRY.register("marking_offset_left", MarkingOffsetLeftBlock::new);
		MARKING_OFFSET_RIGHT = REGISTRY.register("marking_offset_right", MarkingOffsetRightBlock::new);
		MARKING_RIGHT = REGISTRY.register("marking_right", MarkingRightBlock::new);
		MARKING_STRAIGHT = REGISTRY.register("marking_straight", MarkingStraightBlock::new);
		MARKING_STRAIGHT_LEFT = REGISTRY.register("marking_straight_left", MarkingStraightLeftBlock::new);
		MARKING_STRAIGHT_RIGHT = REGISTRY.register("marking_straight_right", MarkingStraightRightBlock::new);
		MARKING_STRAIGHT_UTURN = REGISTRY.register("marking_straight_uturn", MarkingStraightUturnBlock::new);
		MARKING_UTURN = REGISTRY.register("marking_uturn", MarkingUturnBlock::new);
		BLIND_PATH_BAR = REGISTRY.register("blind_path_bar", BlindPathBarBlock::new);
		BLIND_PATH_BAR_SLAB = REGISTRY.register("blind_path_bar_slab", BlindPathBarSlabBlock::new);
		BLIND_PATH_DOT = REGISTRY.register("blind_path_dot", BlindPathDotBlock::new);
		BLIND_PATH_DOT_SLAB = REGISTRY.register("blind_path_dot_slab", BlindPathDotSlabBlock::new);
		BLIND_PATH_BAR_SLOPE = REGISTRY.register("blind_path_bar_slope", BlindPathBarSlopeBlock::new);
		BLIND_PATH_BAR_SLOPE_PRO = REGISTRY.register("blind_path_bar_slope_pro", BlindPathBarSlopeProBlock::new);
		BLIND_PATH_DOT_SLOPE = REGISTRY.register("blind_path_dot_slope", BlindPathDotSlopeBlock::new);
		BLIND_PATH_DOT_SLOPE_PRO = REGISTRY.register("blind_path_dot_slope_pro", BlindPathDotSlopeProBlock::new);
		MARKING_WATCH_FOR_PEDESTRIANS = REGISTRY.register("marking_watch_for_pedestrians", MarkingWatchForPedestriansBlock::new);
		MARKING_60_LOWSPEED = REGISTRY.register("marking_60_lowspeed", Marking60LowspeedBlock::new);
		MARKING_80_LOWSPEED = REGISTRY.register("marking_80_lowspeed", Marking80LowspeedBlock::new);
		MARKING_100_LOWSPEED = REGISTRY.register("marking_100_lowspeed", Marking100LowspeedBlock::new);
		MARKING_40_LOWSPEED = REGISTRY.register("marking_40_lowspeed", Marking40LowspeedBlock::new);
		MARKING_60_HIGHSPEED = REGISTRY.register("marking_60_highspeed", Marking60HighspeedBlock::new);
		MARKING_80_HIGHSPEED = REGISTRY.register("marking_80_highspeed", Marking80HighspeedBlock::new);
		MARKING_100_HIGHSPEED = REGISTRY.register("marking_100_highspeed", Marking100HighspeedBlock::new);
		MARKING_120_HIGHSPEED = REGISTRY.register("marking_120_highspeed", Marking120HighspeedBlock::new);
		TRAFFIC_SIGNAL_POLE = REGISTRY.register("traffic_signal_pole", TrafficSignalPoleBlock::new);
		TRAFFIC_SIGNAL_MAST = REGISTRY.register("traffic_signal_mast", TrafficSignalMastBlock::new);
		ROADSIGN_STOP = REGISTRY.register("roadsign_stop", RoadsignStopBlock::new);
		TRAFFIC_SIGNAL_SMALLPOLE = REGISTRY.register("traffic_signal_smallpole", TrafficSignalSmallpoleBlock::new);
		ROADSIGN_YIELD = REGISTRY.register("roadsign_yield", RoadsignYieldBlock::new);
		ROADSIGN_CROSSROADS = REGISTRY.register("roadsign_crossroads", RoadsignCrossroadsBlock::new);
		ROADSIGN_JUNCTION_LEFT = REGISTRY.register("roadsign_junction_left", RoadsignJunctionLeftBlock::new);
		ROADSIGN_JUNCTION_RIGHT = REGISTRY.register("roadsign_junction_right", RoadsignJunctionRightBlock::new);
		ROADSIGN_JOINING_LEFT = REGISTRY.register("roadsign_joining_left", RoadsignJoiningLeftBlock::new);
		ROADSIGN_JOINING_RIGHT = REGISTRY.register("roadsign_joining_right", RoadsignJoiningRightBlock::new);
		ROADSIGN_DIVERGING_LEFT = REGISTRY.register("roadsign_diverging_left", RoadsignDivergingLeftBlock::new);
		ROADSIGN_DIVERGING_RIGHT = REGISTRY.register("roadsign_diverging_right", RoadsignDivergingRightBlock::new);
		ROADSIGN_ROUNDABOUT = REGISTRY.register("roadsign_roundabout", RoadsignRoundaboutBlock::new);
		ROADSIGN_TURN_LEFT = REGISTRY.register("roadsign_turn_left", RoadsignTurnLeftBlock::new);
		ROADSIGN_TURN_RIGHT = REGISTRY.register("roadsign_turn_right", RoadsignTurnRightBlock::new);
		ROADSIGN_REVERSE_CURVE_LEFT = REGISTRY.register("roadsign_reverse_curve_left", RoadsignReverseCurveLeftBlock::new);
		ROADSIGN_REVERSE_CURVE_RIGHT = REGISTRY.register("roadsign_reverse_curve_right", RoadsignReverseCurveRightBlock::new);
		ROADSIGN_WINDING_LEFT = REGISTRY.register("roadsign_winding_left", RoadsignWindingLeftBlock::new);
		ROADSIGN_WINDING_RIGHT = REGISTRY.register("roadsign_winding_right", RoadsignWindingRightBlock::new);
		ROADSIGN_STEEP_ASCENT = REGISTRY.register("roadsign_steep_ascent", RoadsignSteepAscentBlock::new);
		ROADSIGN_STEEP_DESCENT = REGISTRY.register("roadsign_steep_descent", RoadsignSteepDescentBlock::new);
		ROADSIGN_CONTINUOUS_DESCENT = REGISTRY.register("roadsign_continuous_descent", RoadsignContinuousDescentBlock::new);
		ROADSIGN_NARROWS = REGISTRY.register("roadsign_narrows", RoadsignNarrowsBlock::new);
		ROADSIGN_NARROWS_LEFT = REGISTRY.register("roadsign_narrows_left", RoadsignNarrowsLeftBlock::new);
		ROADSIGN_NARROWS_RIGHT = REGISTRY.register("roadsign_narrows_right", RoadsignNarrowsRightBlock::new);
		ROADSIGN_NARROW_BRIDGE = REGISTRY.register("roadsign_narrow_bridge", RoadsignNarrowBridgeBlock::new);
		ROADSIGN_TWOWAY_TRAFFIC = REGISTRY.register("roadsign_twoway_traffic", RoadsignTwowayTrafficBlock::new);
		ROADSIGN_PEDESTRIANS = REGISTRY.register("roadsign_pedestrians", RoadsignPedestriansBlock::new);
		ROADSIGN_CHILDREN = REGISTRY.register("roadsign_children", RoadsignChildrenBlock::new);
		ROADSIGN_DISABLED_PERSONS = REGISTRY.register("roadsign_disabled_persons", RoadsignDisabledPersonsBlock::new);
		ROADSIGN_NONMOTORIZED_VEHICLES = REGISTRY.register("roadsign_nonmotorized_vehicles", RoadsignNonmotorizedVehiclesBlock::new);
		ROADSIGN_TRAFFIC_SIGNALS = REGISTRY.register("roadsign_traffic_signals", RoadsignTrafficSignalsBlock::new);
		ROADSIGN_FALLINGROCKS_LEFT = REGISTRY.register("roadsign_fallingrocks_left", RoadsignFallingrocksLeftBlock::new);
		ROADSIGN_FALLINGROCKS_RIGHT = REGISTRY.register("roadsign_fallingrocks_right", RoadsignFallingrocksRightBlock::new);
		ROADSIGN_MOUNTAIN_LEFT = REGISTRY.register("roadsign_mountain_left", RoadsignMountainLeftBlock::new);
		ROADSIGN_MOUNTAIN_RIGHT = REGISTRY.register("roadsign_mountain_right", RoadsignMountainRightBlock::new);
		ROADSIGN_VILLAGE = REGISTRY.register("roadsign_village", RoadsignVillageBlock::new);
		ROADSIGN_TUNNEL = REGISTRY.register("roadsign_tunnel", RoadsignTunnelBlock::new);
		ROADSIGN_DANGERS = REGISTRY.register("roadsign_dangers", RoadsignDangersBlock::new);
		ROADSIGN_WORKS = REGISTRY.register("roadsign_works", RoadsignWorksBlock::new);
		ROADSIGN_Y_JUNCTION = REGISTRY.register("roadsign_y_junction", RoadsignYJunctionBlock::new);
		ROADSIGN_T_JUNCTION = REGISTRY.register("roadsign_t_junction", RoadsignTJunctionBlock::new);
		ROADSIGN_NO_ENTRY = REGISTRY.register("roadsign_no_entry", RoadsignNoEntryBlock::new);
		ROADSIGN_NO_THOROUGHFARE = REGISTRY.register("roadsign_no_thoroughfare", RoadsignNoThoroughfareBlock::new);
		ROADSIGN_NO_LEFT_TURN = REGISTRY.register("roadsign_no_left_turn", RoadsignNoLeftTurnBlock::new);
		ROADSIGN_NO_LEFT_OR_RIGHT_TURN = REGISTRY.register("roadsign_no_left_or_right_turn", RoadsignNoLeftOrRightTurnBlock::new);
		ROADSIGN_NO_RIGHT_TURN = REGISTRY.register("roadsign_no_right_turn", RoadsignNoRightTurnBlock::new);
		ROADSIGN_NO_STRAIGHT_AHEAD_OR_LEFT_TURN = REGISTRY.register("roadsign_no_straight_ahead_or_left_turn", RoadsignNoStraightAheadOrLeftTurnBlock::new);
		ROADSIGN_NO_STRAIGHT_AHEAD = REGISTRY.register("roadsign_no_straight_ahead", RoadsignNoStraightAheadBlock::new);
		ROADSIGN_NO_STRAIGHT_AHEAD_OR_RIGHT_TURN = REGISTRY.register("roadsign_no_straight_ahead_or_right_turn", RoadsignNoStraightAheadOrRightTurnBlock::new);
		ROADSIGN_NO_UTURN = REGISTRY.register("roadsign_no_uturn", RoadsignNoUturnBlock::new);
		ROADSIGN_NO_ENTRY_FOR_ARTICULATED_VEHICLES = REGISTRY.register("roadsign_no_entry_for_articulated_vehicles", RoadsignNoEntryForArticulatedVehiclesBlock::new);
		ROADSIGN_NO_ENTRY_FOR_BUSES = REGISTRY.register("roadsign_no_entry_for_buses", RoadsignNoEntryForBusesBlock::new);
		ROADSIGN_NO_ENTRY_FOR_MOTOR_VEHICLES = REGISTRY.register("roadsign_no_entry_for_motor_vehicles", RoadsignNoEntryForMotorVehiclesBlock::new);
		ROADSIGN_NO_ENTRY_FOR_MOTORCYCLES = REGISTRY.register("roadsign_no_entry_for_motorcycles", RoadsignNoEntryForMotorcyclesBlock::new);
		ROADSIGN_NO_ENTRY_FOR_NON_MOTORIZED_VEHICLES = REGISTRY.register("roadsign_no_entry_for_non_motorized_vehicles", RoadsignNoEntryForNonMotorizedVehiclesBlock::new);
		ROADSIGN_NO_ENTRY_FOR_PASSENGER_CARS = REGISTRY.register("roadsign_no_entry_for_passenger_cars", RoadsignNoEntryForPassengerCarsBlock::new);
		ROADSIGN_NO_ENTRY_FOR_PEDESTRIANS = REGISTRY.register("roadsign_no_entry_for_pedestrians", RoadsignNoEntryForPedestriansBlock::new);
		ROADSIGN_NO_ENTRY_FOR_THREE_WHEELED_VEHICLES = REGISTRY.register("roadsign_no_entry_for_three_wheeled_vehicles", RoadsignNoEntryForThreeWheeledVehiclesBlock::new);
		ROADSIGN_NO_ENTRY_FOR_TRACTORS = REGISTRY.register("roadsign_no_entry_for_tractors", RoadsignNoEntryForTractorsBlock::new);
		ROADSIGN_NO_ENTRY_FOR_TRUCKS = REGISTRY.register("roadsign_no_entry_for_trucks", RoadsignNoEntryForTrucksBlock::new);
		ROADSIGN_NO_HONKING = REGISTRY.register("roadsign_no_honking", RoadsignNoHonkingBlock::new);
		ROADSIGN_STOP_FOR_INSPECTION = REGISTRY.register("roadsign_stop_for_inspection", RoadsignStopForInspectionBlock::new);
		ROADSIGN_SPEED_LIMIT_5 = REGISTRY.register("roadsign_speed_limit_5", RoadsignSpeedLimit5Block::new);
		ROADSIGN_SPEED_LIMIT_10 = REGISTRY.register("roadsign_speed_limit_10", RoadsignSpeedLimit10Block::new);
		ROADSIGN_SPEED_LIMIT_15 = REGISTRY.register("roadsign_speed_limit_15", RoadsignSpeedLimit15Block::new);
		ROADSIGN_SPEED_LIMIT_30 = REGISTRY.register("roadsign_speed_limit_30", RoadsignSpeedLimit30Block::new);
		ROADSIGN_SPEED_LIMIT_40 = REGISTRY.register("roadsign_speed_limit_40", RoadsignSpeedLimit40Block::new);
		ROADSIGN_SPEED_LIMIT_60 = REGISTRY.register("roadsign_speed_limit_60", RoadsignSpeedLimit60Block::new);
		ROADSIGN_SPEED_LIMIT_80 = REGISTRY.register("roadsign_speed_limit_80", RoadsignSpeedLimit80Block::new);
		ROADSIGN_SPEED_LIMIT_100 = REGISTRY.register("roadsign_speed_limit_100", RoadsignSpeedLimit100Block::new);
		ROADSIGN_SPEED_LIMIT_120 = REGISTRY.register("roadsign_speed_limit_120", RoadsignSpeedLimit120Block::new);
		ROADSIGN_NO_OVERTAKING = REGISTRY.register("roadsign_no_overtaking", RoadsignNoOvertakingBlock::new);
		ROADSIGN_NO_PARKING = REGISTRY.register("roadsign_no_parking", RoadsignNoParkingBlock::new);
		ROADSIGN_NO_WAITING = REGISTRY.register("roadsign_no_waiting", RoadsignNoWaitingBlock::new);
		ROADSIGN_GIVE_WAY_TO_ONCOMING_VEHICLES = REGISTRY.register("roadsign_give_way_to_oncoming_vehicles", RoadsignGiveWayToOncomingVehiclesBlock::new);
		ROADSIGN_ONLY_TURN_LEFT = REGISTRY.register("roadsign_only_turn_left", RoadsignOnlyTurnLeftBlock::new);
		ROADSIGN_ONLY_TURN_LEFT_OR_RIGHT = REGISTRY.register("roadsign_only_turn_left_or_right", RoadsignOnlyTurnLeftOrRightBlock::new);
		ROADSIGN_ONLY_STRAIGHT_AHEAD_OR_TURN_LEFT = REGISTRY.register("roadsign_only_straight_ahead_or_turn_left", RoadsignOnlyStraightAheadOrTurnLeftBlock::new);
		ROADSIGN_ONLY_STRAIGHT_AHEAD = REGISTRY.register("roadsign_only_straight_ahead", RoadsignOnlyStraightAheadBlock::new);
		ROADSIGN_ONLY_STRAIGHT_AHEAD_OR_TURN_RIGHT = REGISTRY.register("roadsign_only_straight_ahead_or_turn_right", RoadsignOnlyStraightAheadOrTurnRightBlock::new);
		ROADSIGN_KEEP_LEFT = REGISTRY.register("roadsign_keep_left", RoadsignKeepLeftBlock::new);
		ROADSIGN_KEEP_RIGHT = REGISTRY.register("roadsign_keep_right", RoadsignKeepRightBlock::new);
		ROADSIGN_KEEP_ROUNDABOUT = REGISTRY.register("roadsign_keep_roundabout", RoadsignKeepRoundaboutBlock::new);
		ROADSIGN_ONLY_MOTOR_VEHICLES = REGISTRY.register("roadsign_only_motor_vehicles", RoadsignOnlyMotorVehiclesBlock::new);
		ROADSIGN_ONLY_NON_MOTORIZED_VEHICLES = REGISTRY.register("roadsign_only_non_motorized_vehicles", RoadsignOnlyNonMotorizedVehiclesBlock::new);
		ROADSIGN_ONLY_PEDESTRIANS = REGISTRY.register("roadsign_only_pedestrians", RoadsignOnlyPedestriansBlock::new);
		ROADSIGN_SOUND_HORN = REGISTRY.register("roadsign_sound_horn", RoadsignSoundHornBlock::new);
		ROADSIGN_SWITCH_ON_LIGHTS = REGISTRY.register("roadsign_switch_on_lights", RoadsignSwitchOnLightsBlock::new);
		ROADSIGN_MINIMUM_SPEED_LIMIT_40 = REGISTRY.register("roadsign_minimum_speed_limit_40", RoadsignMinimumSpeedLimit40Block::new);
		ROADSIGN_MINIMUM_SPEED_LIMIT_60 = REGISTRY.register("roadsign_minimum_speed_limit_60", RoadsignMinimumSpeedLimit60Block::new);
		ROADSIGN_MINIMUM_SPEED_LIMIT_80 = REGISTRY.register("roadsign_minimum_speed_limit_80", RoadsignMinimumSpeedLimit80Block::new);
		ROADSIGN_MINIMUM_SPEED_LIMIT_100 = REGISTRY.register("roadsign_minimum_speed_limit_100", RoadsignMinimumSpeedLimit100Block::new);
		ROADSIGN_ONLY_TURN_RIGHT = REGISTRY.register("roadsign_only_turn_right", RoadsignOnlyTurnRightBlock::new);
		ROADSIGN_PARKING = REGISTRY.register("roadsign_parking", RoadsignParkingBlock::new);
		ROADSIGN_PARKING_LEFT = REGISTRY.register("roadsign_parking_left", RoadsignParkingLeftBlock::new);
		ROADSIGN_PARKING_RIGHT = REGISTRY.register("roadsign_parking_right", RoadsignParkingRightBlock::new);
		ROADSIGN_PARKING_RESERVED = REGISTRY.register("roadsign_parking_reserved", RoadsignParkingReservedBlock::new);
		ROADSIGN_PARKING_FOR_BUSES = REGISTRY.register("roadsign_parking_for_buses", RoadsignParkingForBusesBlock::new);
		ROADSIGN_PARKING_FOR_SCHOOL_BUSES = REGISTRY.register("roadsign_parking_for_school_buses", RoadsignParkingForSchoolBusesBlock::new);
		ROADSIGN_PARKING_FOR_TAXIS = REGISTRY.register("roadsign_parking_for_taxis", RoadsignParkingForTaxisBlock::new);
		ROADSIGN_PARKING_FOR_EV_CHARGING = REGISTRY.register("roadsign_parking_for_ev_charging", RoadsignParkingForEvChargingBlock::new);
		ROADSIGN_PARKING_FOR_NON_MOTORIZED_VEHICLES = REGISTRY.register("roadsign_parking_for_non_motorized_vehicles", RoadsignParkingForNonMotorizedVehiclesBlock::new);
		ROADSIGN_PARKING_FOR_DISABLED_PERSONS = REGISTRY.register("roadsign_parking_for_disabled_persons", RoadsignParkingForDisabledPersonsBlock::new);
		ROADSIGN_PEDESTRIAN_CROSSING = REGISTRY.register("roadsign_pedestrian_crossing", RoadsignPedestrianCrossingBlock::new);
		ROADSIGN_UTURN = REGISTRY.register("roadsign_uturn", RoadsignUturnBlock::new);
		ROADSIGN_PRIORITY_OVER_ONCOMING_VEHICLES = REGISTRY.register("roadsign_priority_over_oncoming_vehicles", RoadsignPriorityOverOncomingVehiclesBlock::new);
		ROADSIGN_HARD_SHOULDER_AVAILABLE_FOR_TRAFFIC = REGISTRY.register("roadsign_hard_shoulder_available_for_traffic", RoadsignHardShoulderAvailableForTrafficBlock::new);
		ROADSIGN_HARD_SHOULDER_AVAILABLE_END = REGISTRY.register("roadsign_hard_shoulder_available_end", RoadsignHardShoulderAvailableEndBlock::new);
		ROADSIGN_HARD_SHOULDER_AVAILABLE_CLOSE = REGISTRY.register("roadsign_hard_shoulder_available_close", RoadsignHardShoulderAvailableCloseBlock::new);
		ROADSIGN_END_OF_NO_OVERTAKING = REGISTRY.register("roadsign_end_of_no_overtaking", RoadsignEndOfNoOvertakingBlock::new);
		ROADSIGN_END_OF_SPEED_LIMIT_30 = REGISTRY.register("roadsign_end_of_speed_limit_30", RoadsignEndOfSpeedLimit30Block::new);
		ROADSIGN_END_OF_SPEED_LIMIT_40 = REGISTRY.register("roadsign_end_of_speed_limit_40", RoadsignEndOfSpeedLimit40Block::new);
		ROADSIGN_END_OF_SPEED_LIMIT_60 = REGISTRY.register("roadsign_end_of_speed_limit_60", RoadsignEndOfSpeedLimit60Block::new);
		ROADSIGN_END_OF_SPEED_LIMIT_80 = REGISTRY.register("roadsign_end_of_speed_limit_80", RoadsignEndOfSpeedLimit80Block::new);
		ROADSIGN_END_OF_SPEED_LIMIT_100 = REGISTRY.register("roadsign_end_of_speed_limit_100", RoadsignEndOfSpeedLimit100Block::new);
	}
	// Start of user code block custom blocks
	// End of user code block custom blocks
}