/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.flyaway.ncbroadblck.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.flyaway.ncbroadblck.item.SunglassesItem;
import net.flyaway.ncbroadblck.item.ElectricWrenchItem;
import net.flyaway.ncbroadblck.NcbRoadblckMod;

public class NcbRoadblckModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(NcbRoadblckMod.MODID);
	public static final DeferredItem<Item> ASPHALT_ROAD;
	public static final DeferredItem<Item> ASPHALT_ROAD_SLAB;
	public static final DeferredItem<Item> ASPHALT_ROAD_PLATE;
	public static final DeferredItem<Item> ASPHALT_ROAD_SLOPE;
	public static final DeferredItem<Item> ASPHALT_ROAD_SLOPE_PRO;
	public static final DeferredItem<Item> ASPHALT_3_COLOR_LINE;
	public static final DeferredItem<Item> ASPHALT_YELLOW_LINK;
	public static final DeferredItem<Item> ASPHALT_WHITE_WIDELINK;
	public static final DeferredItem<Item> ASPHALT_YELLOW_WIDELINK;
	public static final DeferredItem<Item> ASPHALT_WHITE_LINK;
	public static final DeferredItem<Item> ASPHALT_WHITE_LINE;
	public static final DeferredItem<Item> ASPHALT_YELLOW_2_LINE;
	public static final DeferredItem<Item> ASPHALT_YELLOW_LINE;
	public static final DeferredItem<Item> ASPHALT_3_COLOR_LINE_SLAB;
	public static final DeferredItem<Item> ASPHALT_WHITE_LINK_SLAB;
	public static final DeferredItem<Item> ASPHALT_WHITE_WIDELINK_SLAB;
	public static final DeferredItem<Item> ASPHALT_YELLOW_LINK_SLAB;
	public static final DeferredItem<Item> ASPHALT_YELLOW_WIDELINK_SLAB;
	public static final DeferredItem<Item> ASPHALT_WHITE_LINE_SLAB;
	public static final DeferredItem<Item> ASPHALT_YELLOW_LINE_SLAB;
	public static final DeferredItem<Item> ASPHALT_YELLOW_2_LINE_SLAB;
	public static final DeferredItem<Item> ASPHALT_3_COLOR_LINE_SLOPE;
	public static final DeferredItem<Item> ASPHALT_3_COLOR_LINE_SLOPE_PRO;
	public static final DeferredItem<Item> ASPHALT_3_COLOR_LINE_PLATE;
	public static final DeferredItem<Item> ASPHALT_WHITE_LINE_PLATE;
	public static final DeferredItem<Item> ASPHALT_WHITE_LINE_SLOPE;
	public static final DeferredItem<Item> ASPHALT_WHITE_LINE_SLOPE_PRO;
	public static final DeferredItem<Item> ASPHALT_YELLOW_2_LINE_PLATE;
	public static final DeferredItem<Item> ASPHALT_YELLOW_2_LINE_SLOPE;
	public static final DeferredItem<Item> ASPHALT_YELLOW_2_LINE_SLOPE_PRO;
	public static final DeferredItem<Item> ASPHALT_YELLOW_LINE_PLATE;
	public static final DeferredItem<Item> ASPHALT_YELLOW_LINE_SLOPE;
	public static final DeferredItem<Item> ASPHALT_YELLOW_LINE_SLOPE_PRO;
	public static final DeferredItem<Item> ASPHALT_YELLOW_GRIDLINE;
	public static final DeferredItem<Item> ASPHALT_YELLOW_GRIDLINE_SLAB;
	public static final DeferredItem<Item> ASPHALT_WHITE_GRIDLINE;
	public static final DeferredItem<Item> ASPHALT_WHITE_GRIDLINE_SLAB;
	public static final DeferredItem<Item> ASPHALT_YELLOW_FRAME;
	public static final DeferredItem<Item> ASPHALT_WHITE_FRAME;
	public static final DeferredItem<Item> ASPHALT_YELLOW_FRAME_SLAB;
	public static final DeferredItem<Item> ASPHALT_WHITE_FRAME_SLAB;
	public static final DeferredItem<Item> ASPHALT_YELLOW_SLASH;
	public static final DeferredItem<Item> ASPHALT_YELLOW_SLASH_SLAB;
	public static final DeferredItem<Item> ASPHALT_WHITE_SLASH;
	public static final DeferredItem<Item> ASPHALT_WHITE_SLASH_SLAB;
	public static final DeferredItem<Item> ASPHALT_YELLOW_BACKSLASH;
	public static final DeferredItem<Item> ASPHALT_YELLOW_BACKSLASH_SLAB;
	public static final DeferredItem<Item> ASPHALT_WHITE_BACKSLASH;
	public static final DeferredItem<Item> ASPHALT_WHITE_BACKSLASH_SLAB;
	public static final DeferredItem<Item> ASPHALT_YELLOW_LINESLASH;
	public static final DeferredItem<Item> ASPHALT_YELLOW_LINESLASH_SLAB;
	public static final DeferredItem<Item> ASPHALT_WHITE_LINESLASH;
	public static final DeferredItem<Item> ASPHALT_WHITE_LINESLASH_SLAB;
	public static final DeferredItem<Item> ASPHALT_YELLOW_2_LINESLASH;
	public static final DeferredItem<Item> ASPHALT_YELLOW_2_LINESLASH_SLAB;
	public static final DeferredItem<Item> ASPHALT_3_COLOR_LINESLASH;
	public static final DeferredItem<Item> ASPHALT_3_COLOR_LINESLASH_SLAB;
	public static final DeferredItem<Item> PAVERS_CHECKERED_GRAY;
	public static final DeferredItem<Item> PAVERS_CHECKERED_GRAY_SLAB;
	public static final DeferredItem<Item> PAVERS_CHECKERED_GRAY_PLATE;
	public static final DeferredItem<Item> PAVERS_CHECKERED_GRAY_SLOPE;
	public static final DeferredItem<Item> PAVERS_CHECKERED_GRAY_SLOPE_PRO;
	public static final DeferredItem<Item> PAVERS_CHECKERED_GREEN;
	public static final DeferredItem<Item> PAVERS_CHECKERED_GREEN_SLAB;
	public static final DeferredItem<Item> PAVERS_CHECKERED_GREEN_PLATE;
	public static final DeferredItem<Item> PAVERS_CHECKERED_GREEN_SLOPE;
	public static final DeferredItem<Item> PAVERS_CHECKERED_GREEN_SLOPE_PRO;
	public static final DeferredItem<Item> PAVERS_CHECKERED_RED;
	public static final DeferredItem<Item> PAVERS_CHECKERED_RED_SLAB;
	public static final DeferredItem<Item> PAVERS_CHECKERED_RED_PLATE;
	public static final DeferredItem<Item> PAVERS_CHECKERED_RED_SLOPE;
	public static final DeferredItem<Item> PAVERS_CHECKERED_RED_SLOPE_PRO;
	public static final DeferredItem<Item> PAVERS_CHECKERED_YELLOW;
	public static final DeferredItem<Item> PAVERS_CHECKERED_YELLOW_SLAB;
	public static final DeferredItem<Item> PAVERS_CHECKERED_YELLOW_PLATE;
	public static final DeferredItem<Item> PAVERS_CHECKERED_YELLOW_SLOPE;
	public static final DeferredItem<Item> PAVERS_CHECKERED_YELLOW_SLOPE_PRO;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_GRAY;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_GRAY_SLAB;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_GRAY_PLATE;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_GRAY_SLOPE;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_GRAY_SLOPE_PRO;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_GREEN;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_GREEN_SLAB;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_GREEN_PLATE;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_GREEN_SLOPE;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_GREEN_SLOPE_PRO;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_RED;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_RED_SLAB;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_RED_PLATE;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_RED_SLOPE;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_RED_SLOPE_PRO;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_YELLOW;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_YELLOW_SLAB;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_YELLOW_PLATE;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_YELLOW_SLOPE;
	public static final DeferredItem<Item> PAVERS_INTERLOCK_YELLOW_SLOPE_PRO;
	public static final DeferredItem<Item> PAVERS_SQUARE_GRAY;
	public static final DeferredItem<Item> PAVERS_SQUARE_GRAY_SLAB;
	public static final DeferredItem<Item> PAVERS_SQUARE_GRAY_PLATE;
	public static final DeferredItem<Item> PAVERS_SQUARE_GRAY_SLOPE;
	public static final DeferredItem<Item> PAVERS_SQUARE_GRAY_SLOPE_PRO;
	public static final DeferredItem<Item> PAVERS_SQUARE_GREEN;
	public static final DeferredItem<Item> PAVERS_SQUARE_GREEN_SLAB;
	public static final DeferredItem<Item> PAVERS_SQUARE_GREEN_PLATE;
	public static final DeferredItem<Item> PAVERS_SQUARE_GREEN_SLOPE;
	public static final DeferredItem<Item> PAVERS_SQUARE_GREEN_SLOPE_PRO;
	public static final DeferredItem<Item> PAVERS_SQUARE_RED;
	public static final DeferredItem<Item> PAVERS_SQUARE_RED_SLAB;
	public static final DeferredItem<Item> PAVERS_SQUARE_RED_PLATE;
	public static final DeferredItem<Item> PAVERS_SQUARE_RED_SLOPE;
	public static final DeferredItem<Item> PAVERS_SQUARE_RED_SLOPE_PRO;
	public static final DeferredItem<Item> PAVERS_SQUARE_YELLOW;
	public static final DeferredItem<Item> PAVERS_SQUARE_YELLOW_SLAB;
	public static final DeferredItem<Item> PAVERS_SQUARE_YELLOW_PLATE;
	public static final DeferredItem<Item> PAVERS_SQUARE_YELLOW_SLOPE;
	public static final DeferredItem<Item> PAVERS_SQUARE_YELLOW_SLOPE_PRO;
	public static final DeferredItem<Item> ASPHALT_TIDELINE;
	public static final DeferredItem<Item> ASPHALT_TIDELINE_SLAB;
	public static final DeferredItem<Item> ASPHALT_TIDELINE_L_SLAB;
	public static final DeferredItem<Item> ASPHALT_TIDELINE_R_SLAB;
	public static final DeferredItem<Item> ASPHALT_TIDELINE_L;
	public static final DeferredItem<Item> ASPHALT_TIDELINE_R;
	public static final DeferredItem<Item> ASPHALT_WHITE_WIDELINE;
	public static final DeferredItem<Item> ASPHALT_WHITE_WIDELINE_SLAB;
	public static final DeferredItem<Item> ASPHALT_SOLID_AND_DOTTED_LINE;
	public static final DeferredItem<Item> ASPHALT_SOLID_AND_DOTTED_LINE_SLAB;
	public static final DeferredItem<Item> ASPHALT_YIELD_LINE;
	public static final DeferredItem<Item> ASPHALT_YIELD_LINE_SLAB;
	public static final DeferredItem<Item> SHOULDER_ASPHALT;
	public static final DeferredItem<Item> SHOULDER_ASPHALT_SLAB;
	public static final DeferredItem<Item> SHOULDER_MARBLE;
	public static final DeferredItem<Item> SHOULDER_MARBLE_SLAB;
	public static final DeferredItem<Item> MARBLE;
	public static final DeferredItem<Item> MARBLE_SLAB;
	public static final DeferredItem<Item> CEMENT;
	public static final DeferredItem<Item> CEMENT_SLAB;
	public static final DeferredItem<Item> PATTERN_STEEL;
	public static final DeferredItem<Item> PATTERN_STEEL_SLAB;
	public static final DeferredItem<Item> SHOULDER_ASPHALT_L_SLOPE;
	public static final DeferredItem<Item> SHOULDER_ASPHALT_R_SLOPE;
	public static final DeferredItem<Item> SHOULDER_ASPHALT_L_SLOPE_PRO;
	public static final DeferredItem<Item> SHOULDER_ASPHALT_R_SLOPE_PRO;
	public static final DeferredItem<Item> SHOULDER_MARBLE_L_SLOPE;
	public static final DeferredItem<Item> SHOULDER_MARBLE_R_SLOPE;
	public static final DeferredItem<Item> SHOULDER_MARBLE_L_SLOPE_PRO;
	public static final DeferredItem<Item> SHOULDER_MARBLE_R_SLOPE_PRO;
	public static final DeferredItem<Item> SHOULDER_ASPHALT_SLASH;
	public static final DeferredItem<Item> SHOULDER_ASPHALT_SLASH_SLAB;
	public static final DeferredItem<Item> SHOULDER_MARBLE_SLASH;
	public static final DeferredItem<Item> SHOULDER_MARBLE_SLASH_SLAB;
	public static final DeferredItem<Item> SHOULDER_RAINGRATE;
	public static final DeferredItem<Item> SHOULDER_RAINGRATE_SLAB;
	public static final DeferredItem<Item> ELECTRIC_WRENCH;
	public static final DeferredItem<Item> BOLLARD_SIDEWALK;
	public static final DeferredItem<Item> STONE_PILLAR;
	public static final DeferredItem<Item> SPEED_BUMP;
	public static final DeferredItem<Item> GUARDRAIL;
	public static final DeferredItem<Item> GUARDRAIL_SMALL;
	public static final DeferredItem<Item> MARKING_LEFT;
	public static final DeferredItem<Item> MARKING_LEFT_RIGHT;
	public static final DeferredItem<Item> MARKING_LEFT_UTURN;
	public static final DeferredItem<Item> MARKING_OFFSET_LEFT;
	public static final DeferredItem<Item> MARKING_OFFSET_RIGHT;
	public static final DeferredItem<Item> MARKING_RIGHT;
	public static final DeferredItem<Item> MARKING_STRAIGHT;
	public static final DeferredItem<Item> MARKING_STRAIGHT_LEFT;
	public static final DeferredItem<Item> MARKING_STRAIGHT_RIGHT;
	public static final DeferredItem<Item> MARKING_STRAIGHT_UTURN;
	public static final DeferredItem<Item> MARKING_UTURN;
	public static final DeferredItem<Item> SUNGLASSES;
	public static final DeferredItem<Item> BLIND_PATH_BAR;
	public static final DeferredItem<Item> BLIND_PATH_BAR_SLAB;
	public static final DeferredItem<Item> BLIND_PATH_DOT;
	public static final DeferredItem<Item> BLIND_PATH_DOT_SLAB;
	public static final DeferredItem<Item> BLIND_PATH_BAR_SLOPE;
	public static final DeferredItem<Item> BLIND_PATH_BAR_SLOPE_PRO;
	public static final DeferredItem<Item> BLIND_PATH_DOT_SLOPE;
	public static final DeferredItem<Item> BLIND_PATH_DOT_SLOPE_PRO;
	public static final DeferredItem<Item> MARKING_WATCH_FOR_PEDESTRIANS;
	public static final DeferredItem<Item> MARKING_60_LOWSPEED;
	public static final DeferredItem<Item> MARKING_80_LOWSPEED;
	public static final DeferredItem<Item> MARKING_100_LOWSPEED;
	public static final DeferredItem<Item> MARKING_40_LOWSPEED;
	public static final DeferredItem<Item> MARKING_60_HIGHSPEED;
	public static final DeferredItem<Item> MARKING_80_HIGHSPEED;
	public static final DeferredItem<Item> MARKING_100_HIGHSPEED;
	public static final DeferredItem<Item> MARKING_120_HIGHSPEED;
	public static final DeferredItem<Item> TRAFFIC_SIGNAL_POLE;
	public static final DeferredItem<Item> TRAFFIC_SIGNAL_MAST;
	public static final DeferredItem<Item> ROADSIGN_STOP;
	public static final DeferredItem<Item> TRAFFIC_SIGNAL_SMALLPOLE;
	public static final DeferredItem<Item> ROADSIGN_YIELD;
	public static final DeferredItem<Item> ROADSIGN_CROSSROADS;
	public static final DeferredItem<Item> ROADSIGN_JUNCTION_LEFT;
	public static final DeferredItem<Item> ROADSIGN_JUNCTION_RIGHT;
	public static final DeferredItem<Item> ROADSIGN_JOINING_LEFT;
	public static final DeferredItem<Item> ROADSIGN_JOINING_RIGHT;
	public static final DeferredItem<Item> ROADSIGN_DIVERGING_LEFT;
	public static final DeferredItem<Item> ROADSIGN_DIVERGING_RIGHT;
	public static final DeferredItem<Item> ROADSIGN_ROUNDABOUT;
	public static final DeferredItem<Item> ROADSIGN_TURN_LEFT;
	public static final DeferredItem<Item> ROADSIGN_TURN_RIGHT;
	public static final DeferredItem<Item> ROADSIGN_REVERSE_CURVE_LEFT;
	public static final DeferredItem<Item> ROADSIGN_REVERSE_CURVE_RIGHT;
	public static final DeferredItem<Item> ROADSIGN_WINDING_LEFT;
	public static final DeferredItem<Item> ROADSIGN_WINDING_RIGHT;
	public static final DeferredItem<Item> ROADSIGN_STEEP_ASCENT;
	public static final DeferredItem<Item> ROADSIGN_STEEP_DESCENT;
	public static final DeferredItem<Item> ROADSIGN_CONTINUOUS_DESCENT;
	public static final DeferredItem<Item> ROADSIGN_NARROWS;
	public static final DeferredItem<Item> ROADSIGN_NARROWS_LEFT;
	public static final DeferredItem<Item> ROADSIGN_NARROWS_RIGHT;
	public static final DeferredItem<Item> ROADSIGN_NARROW_BRIDGE;
	public static final DeferredItem<Item> ROADSIGN_TWOWAY_TRAFFIC;
	public static final DeferredItem<Item> ROADSIGN_PEDESTRIANS;
	public static final DeferredItem<Item> ROADSIGN_CHILDREN;
	public static final DeferredItem<Item> ROADSIGN_DISABLED_PERSONS;
	public static final DeferredItem<Item> ROADSIGN_NONMOTORIZED_VEHICLES;
	public static final DeferredItem<Item> ROADSIGN_TRAFFIC_SIGNALS;
	public static final DeferredItem<Item> ROADSIGN_FALLINGROCKS_LEFT;
	public static final DeferredItem<Item> ROADSIGN_FALLINGROCKS_RIGHT;
	public static final DeferredItem<Item> ROADSIGN_MOUNTAIN_LEFT;
	public static final DeferredItem<Item> ROADSIGN_MOUNTAIN_RIGHT;
	public static final DeferredItem<Item> ROADSIGN_VILLAGE;
	public static final DeferredItem<Item> ROADSIGN_TUNNEL;
	public static final DeferredItem<Item> ROADSIGN_DANGERS;
	public static final DeferredItem<Item> ROADSIGN_WORKS;
	public static final DeferredItem<Item> ROADSIGN_Y_JUNCTION;
	public static final DeferredItem<Item> ROADSIGN_T_JUNCTION;
	public static final DeferredItem<Item> ROADSIGN_NO_ENTRY;
	public static final DeferredItem<Item> ROADSIGN_NO_THOROUGHFARE;
	public static final DeferredItem<Item> ROADSIGN_NO_LEFT_TURN;
	public static final DeferredItem<Item> ROADSIGN_NO_LEFT_OR_RIGHT_TURN;
	public static final DeferredItem<Item> ROADSIGN_NO_RIGHT_TURN;
	public static final DeferredItem<Item> ROADSIGN_NO_STRAIGHT_AHEAD_OR_LEFT_TURN;
	public static final DeferredItem<Item> ROADSIGN_NO_STRAIGHT_AHEAD;
	public static final DeferredItem<Item> ROADSIGN_NO_STRAIGHT_AHEAD_OR_RIGHT_TURN;
	public static final DeferredItem<Item> ROADSIGN_NO_UTURN;
	public static final DeferredItem<Item> ROADSIGN_NO_ENTRY_FOR_ARTICULATED_VEHICLES;
	public static final DeferredItem<Item> ROADSIGN_NO_ENTRY_FOR_BUSES;
	public static final DeferredItem<Item> ROADSIGN_NO_ENTRY_FOR_MOTOR_VEHICLES;
	public static final DeferredItem<Item> ROADSIGN_NO_ENTRY_FOR_MOTORCYCLES;
	public static final DeferredItem<Item> ROADSIGN_NO_ENTRY_FOR_NON_MOTORIZED_VEHICLES;
	public static final DeferredItem<Item> ROADSIGN_NO_ENTRY_FOR_PASSENGER_CARS;
	public static final DeferredItem<Item> ROADSIGN_NO_ENTRY_FOR_PEDESTRIANS;
	public static final DeferredItem<Item> ROADSIGN_NO_ENTRY_FOR_THREE_WHEELED_VEHICLES;
	public static final DeferredItem<Item> ROADSIGN_NO_ENTRY_FOR_TRACTORS;
	public static final DeferredItem<Item> ROADSIGN_NO_ENTRY_FOR_TRUCKS;
	public static final DeferredItem<Item> ROADSIGN_NO_HONKING;
	public static final DeferredItem<Item> ROADSIGN_STOP_FOR_INSPECTION;
	public static final DeferredItem<Item> ROADSIGN_SPEED_LIMIT_5;
	public static final DeferredItem<Item> ROADSIGN_SPEED_LIMIT_10;
	public static final DeferredItem<Item> ROADSIGN_SPEED_LIMIT_15;
	public static final DeferredItem<Item> ROADSIGN_SPEED_LIMIT_30;
	public static final DeferredItem<Item> ROADSIGN_SPEED_LIMIT_40;
	public static final DeferredItem<Item> ROADSIGN_SPEED_LIMIT_60;
	public static final DeferredItem<Item> ROADSIGN_SPEED_LIMIT_80;
	public static final DeferredItem<Item> ROADSIGN_SPEED_LIMIT_100;
	public static final DeferredItem<Item> ROADSIGN_SPEED_LIMIT_120;
	public static final DeferredItem<Item> ROADSIGN_NO_OVERTAKING;
	public static final DeferredItem<Item> ROADSIGN_NO_PARKING;
	public static final DeferredItem<Item> ROADSIGN_NO_WAITING;
	public static final DeferredItem<Item> ROADSIGN_GIVE_WAY_TO_ONCOMING_VEHICLES;
	public static final DeferredItem<Item> ROADSIGN_ONLY_TURN_LEFT;
	public static final DeferredItem<Item> ROADSIGN_ONLY_TURN_LEFT_OR_RIGHT;
	public static final DeferredItem<Item> ROADSIGN_ONLY_STRAIGHT_AHEAD_OR_TURN_LEFT;
	public static final DeferredItem<Item> ROADSIGN_ONLY_STRAIGHT_AHEAD;
	public static final DeferredItem<Item> ROADSIGN_ONLY_STRAIGHT_AHEAD_OR_TURN_RIGHT;
	public static final DeferredItem<Item> ROADSIGN_KEEP_LEFT;
	public static final DeferredItem<Item> ROADSIGN_KEEP_RIGHT;
	public static final DeferredItem<Item> ROADSIGN_KEEP_ROUNDABOUT;
	public static final DeferredItem<Item> ROADSIGN_ONLY_MOTOR_VEHICLES;
	public static final DeferredItem<Item> ROADSIGN_ONLY_NON_MOTORIZED_VEHICLES;
	public static final DeferredItem<Item> ROADSIGN_ONLY_PEDESTRIANS;
	public static final DeferredItem<Item> ROADSIGN_SOUND_HORN;
	public static final DeferredItem<Item> ROADSIGN_SWITCH_ON_LIGHTS;
	public static final DeferredItem<Item> ROADSIGN_MINIMUM_SPEED_LIMIT_40;
	public static final DeferredItem<Item> ROADSIGN_MINIMUM_SPEED_LIMIT_60;
	public static final DeferredItem<Item> ROADSIGN_MINIMUM_SPEED_LIMIT_80;
	public static final DeferredItem<Item> ROADSIGN_MINIMUM_SPEED_LIMIT_100;
	public static final DeferredItem<Item> ROADSIGN_ONLY_TURN_RIGHT;
	public static final DeferredItem<Item> ROADSIGN_PARKING;
	public static final DeferredItem<Item> ROADSIGN_PARKING_LEFT;
	public static final DeferredItem<Item> ROADSIGN_PARKING_RIGHT;
	public static final DeferredItem<Item> ROADSIGN_PARKING_RESERVED;
	public static final DeferredItem<Item> ROADSIGN_PARKING_FOR_BUSES;
	public static final DeferredItem<Item> ROADSIGN_PARKING_FOR_SCHOOL_BUSES;
	public static final DeferredItem<Item> ROADSIGN_PARKING_FOR_TAXIS;
	public static final DeferredItem<Item> ROADSIGN_PARKING_FOR_EV_CHARGING;
	public static final DeferredItem<Item> ROADSIGN_PARKING_FOR_NON_MOTORIZED_VEHICLES;
	public static final DeferredItem<Item> ROADSIGN_PARKING_FOR_DISABLED_PERSONS;
	public static final DeferredItem<Item> ROADSIGN_PEDESTRIAN_CROSSING;
	public static final DeferredItem<Item> ROADSIGN_UTURN;
	public static final DeferredItem<Item> ROADSIGN_PRIORITY_OVER_ONCOMING_VEHICLES;
	public static final DeferredItem<Item> ROADSIGN_HARD_SHOULDER_AVAILABLE_FOR_TRAFFIC;
	public static final DeferredItem<Item> ROADSIGN_HARD_SHOULDER_AVAILABLE_END;
	public static final DeferredItem<Item> ROADSIGN_HARD_SHOULDER_AVAILABLE_CLOSE;
	public static final DeferredItem<Item> ROADSIGN_END_OF_NO_OVERTAKING;
	public static final DeferredItem<Item> ROADSIGN_END_OF_SPEED_LIMIT_30;
	public static final DeferredItem<Item> ROADSIGN_END_OF_SPEED_LIMIT_40;
	public static final DeferredItem<Item> ROADSIGN_END_OF_SPEED_LIMIT_60;
	public static final DeferredItem<Item> ROADSIGN_END_OF_SPEED_LIMIT_80;
	public static final DeferredItem<Item> ROADSIGN_END_OF_SPEED_LIMIT_100;
	public static final DeferredItem<Item> MANHOLE_COVER;
	public static final DeferredItem<Item> CEMENT_HIGH_DENSITY;
	public static final DeferredItem<Item> CEMENT_HIGH_DENSITY_SLAB;
	static {
		ASPHALT_ROAD = block(NcbRoadblckModBlocks.ASPHALT_ROAD);
		ASPHALT_ROAD_SLAB = block(NcbRoadblckModBlocks.ASPHALT_ROAD_SLAB);
		ASPHALT_ROAD_PLATE = block(NcbRoadblckModBlocks.ASPHALT_ROAD_PLATE);
		ASPHALT_ROAD_SLOPE = block(NcbRoadblckModBlocks.ASPHALT_ROAD_SLOPE);
		ASPHALT_ROAD_SLOPE_PRO = block(NcbRoadblckModBlocks.ASPHALT_ROAD_SLOPE_PRO);
		ASPHALT_3_COLOR_LINE = block(NcbRoadblckModBlocks.ASPHALT_3_COLOR_LINE);
		ASPHALT_YELLOW_LINK = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_LINK);
		ASPHALT_WHITE_WIDELINK = block(NcbRoadblckModBlocks.ASPHALT_WHITE_WIDELINK);
		ASPHALT_YELLOW_WIDELINK = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_WIDELINK);
		ASPHALT_WHITE_LINK = block(NcbRoadblckModBlocks.ASPHALT_WHITE_LINK);
		ASPHALT_WHITE_LINE = block(NcbRoadblckModBlocks.ASPHALT_WHITE_LINE);
		ASPHALT_YELLOW_2_LINE = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_2_LINE);
		ASPHALT_YELLOW_LINE = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_LINE);
		ASPHALT_3_COLOR_LINE_SLAB = block(NcbRoadblckModBlocks.ASPHALT_3_COLOR_LINE_SLAB);
		ASPHALT_WHITE_LINK_SLAB = block(NcbRoadblckModBlocks.ASPHALT_WHITE_LINK_SLAB);
		ASPHALT_WHITE_WIDELINK_SLAB = block(NcbRoadblckModBlocks.ASPHALT_WHITE_WIDELINK_SLAB);
		ASPHALT_YELLOW_LINK_SLAB = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_LINK_SLAB);
		ASPHALT_YELLOW_WIDELINK_SLAB = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_WIDELINK_SLAB);
		ASPHALT_WHITE_LINE_SLAB = block(NcbRoadblckModBlocks.ASPHALT_WHITE_LINE_SLAB);
		ASPHALT_YELLOW_LINE_SLAB = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_LINE_SLAB);
		ASPHALT_YELLOW_2_LINE_SLAB = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_2_LINE_SLAB);
		ASPHALT_3_COLOR_LINE_SLOPE = block(NcbRoadblckModBlocks.ASPHALT_3_COLOR_LINE_SLOPE);
		ASPHALT_3_COLOR_LINE_SLOPE_PRO = block(NcbRoadblckModBlocks.ASPHALT_3_COLOR_LINE_SLOPE_PRO);
		ASPHALT_3_COLOR_LINE_PLATE = block(NcbRoadblckModBlocks.ASPHALT_3_COLOR_LINE_PLATE);
		ASPHALT_WHITE_LINE_PLATE = block(NcbRoadblckModBlocks.ASPHALT_WHITE_LINE_PLATE);
		ASPHALT_WHITE_LINE_SLOPE = block(NcbRoadblckModBlocks.ASPHALT_WHITE_LINE_SLOPE);
		ASPHALT_WHITE_LINE_SLOPE_PRO = block(NcbRoadblckModBlocks.ASPHALT_WHITE_LINE_SLOPE_PRO);
		ASPHALT_YELLOW_2_LINE_PLATE = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_2_LINE_PLATE);
		ASPHALT_YELLOW_2_LINE_SLOPE = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_2_LINE_SLOPE);
		ASPHALT_YELLOW_2_LINE_SLOPE_PRO = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_2_LINE_SLOPE_PRO);
		ASPHALT_YELLOW_LINE_PLATE = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_LINE_PLATE);
		ASPHALT_YELLOW_LINE_SLOPE = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_LINE_SLOPE);
		ASPHALT_YELLOW_LINE_SLOPE_PRO = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_LINE_SLOPE_PRO);
		ASPHALT_YELLOW_GRIDLINE = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_GRIDLINE);
		ASPHALT_YELLOW_GRIDLINE_SLAB = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_GRIDLINE_SLAB);
		ASPHALT_WHITE_GRIDLINE = block(NcbRoadblckModBlocks.ASPHALT_WHITE_GRIDLINE);
		ASPHALT_WHITE_GRIDLINE_SLAB = block(NcbRoadblckModBlocks.ASPHALT_WHITE_GRIDLINE_SLAB);
		ASPHALT_YELLOW_FRAME = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_FRAME);
		ASPHALT_WHITE_FRAME = block(NcbRoadblckModBlocks.ASPHALT_WHITE_FRAME);
		ASPHALT_YELLOW_FRAME_SLAB = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_FRAME_SLAB);
		ASPHALT_WHITE_FRAME_SLAB = block(NcbRoadblckModBlocks.ASPHALT_WHITE_FRAME_SLAB);
		ASPHALT_YELLOW_SLASH = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_SLASH);
		ASPHALT_YELLOW_SLASH_SLAB = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_SLASH_SLAB);
		ASPHALT_WHITE_SLASH = block(NcbRoadblckModBlocks.ASPHALT_WHITE_SLASH);
		ASPHALT_WHITE_SLASH_SLAB = block(NcbRoadblckModBlocks.ASPHALT_WHITE_SLASH_SLAB);
		ASPHALT_YELLOW_BACKSLASH = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_BACKSLASH);
		ASPHALT_YELLOW_BACKSLASH_SLAB = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_BACKSLASH_SLAB);
		ASPHALT_WHITE_BACKSLASH = block(NcbRoadblckModBlocks.ASPHALT_WHITE_BACKSLASH);
		ASPHALT_WHITE_BACKSLASH_SLAB = block(NcbRoadblckModBlocks.ASPHALT_WHITE_BACKSLASH_SLAB);
		ASPHALT_YELLOW_LINESLASH = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_LINESLASH);
		ASPHALT_YELLOW_LINESLASH_SLAB = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_LINESLASH_SLAB);
		ASPHALT_WHITE_LINESLASH = block(NcbRoadblckModBlocks.ASPHALT_WHITE_LINESLASH);
		ASPHALT_WHITE_LINESLASH_SLAB = block(NcbRoadblckModBlocks.ASPHALT_WHITE_LINESLASH_SLAB);
		ASPHALT_YELLOW_2_LINESLASH = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_2_LINESLASH);
		ASPHALT_YELLOW_2_LINESLASH_SLAB = block(NcbRoadblckModBlocks.ASPHALT_YELLOW_2_LINESLASH_SLAB);
		ASPHALT_3_COLOR_LINESLASH = block(NcbRoadblckModBlocks.ASPHALT_3_COLOR_LINESLASH);
		ASPHALT_3_COLOR_LINESLASH_SLAB = block(NcbRoadblckModBlocks.ASPHALT_3_COLOR_LINESLASH_SLAB);
		PAVERS_CHECKERED_GRAY = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_GRAY);
		PAVERS_CHECKERED_GRAY_SLAB = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_GRAY_SLAB);
		PAVERS_CHECKERED_GRAY_PLATE = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_GRAY_PLATE);
		PAVERS_CHECKERED_GRAY_SLOPE = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_GRAY_SLOPE);
		PAVERS_CHECKERED_GRAY_SLOPE_PRO = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_GRAY_SLOPE_PRO);
		PAVERS_CHECKERED_GREEN = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_GREEN);
		PAVERS_CHECKERED_GREEN_SLAB = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_GREEN_SLAB);
		PAVERS_CHECKERED_GREEN_PLATE = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_GREEN_PLATE);
		PAVERS_CHECKERED_GREEN_SLOPE = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_GREEN_SLOPE);
		PAVERS_CHECKERED_GREEN_SLOPE_PRO = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_GREEN_SLOPE_PRO);
		PAVERS_CHECKERED_RED = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_RED);
		PAVERS_CHECKERED_RED_SLAB = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_RED_SLAB);
		PAVERS_CHECKERED_RED_PLATE = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_RED_PLATE);
		PAVERS_CHECKERED_RED_SLOPE = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_RED_SLOPE);
		PAVERS_CHECKERED_RED_SLOPE_PRO = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_RED_SLOPE_PRO);
		PAVERS_CHECKERED_YELLOW = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_YELLOW);
		PAVERS_CHECKERED_YELLOW_SLAB = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_YELLOW_SLAB);
		PAVERS_CHECKERED_YELLOW_PLATE = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_YELLOW_PLATE);
		PAVERS_CHECKERED_YELLOW_SLOPE = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_YELLOW_SLOPE);
		PAVERS_CHECKERED_YELLOW_SLOPE_PRO = block(NcbRoadblckModBlocks.PAVERS_CHECKERED_YELLOW_SLOPE_PRO);
		PAVERS_INTERLOCK_GRAY = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_GRAY);
		PAVERS_INTERLOCK_GRAY_SLAB = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_GRAY_SLAB);
		PAVERS_INTERLOCK_GRAY_PLATE = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_GRAY_PLATE);
		PAVERS_INTERLOCK_GRAY_SLOPE = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_GRAY_SLOPE);
		PAVERS_INTERLOCK_GRAY_SLOPE_PRO = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_GRAY_SLOPE_PRO);
		PAVERS_INTERLOCK_GREEN = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_GREEN);
		PAVERS_INTERLOCK_GREEN_SLAB = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_GREEN_SLAB);
		PAVERS_INTERLOCK_GREEN_PLATE = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_GREEN_PLATE);
		PAVERS_INTERLOCK_GREEN_SLOPE = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_GREEN_SLOPE);
		PAVERS_INTERLOCK_GREEN_SLOPE_PRO = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_GREEN_SLOPE_PRO);
		PAVERS_INTERLOCK_RED = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_RED);
		PAVERS_INTERLOCK_RED_SLAB = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_RED_SLAB);
		PAVERS_INTERLOCK_RED_PLATE = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_RED_PLATE);
		PAVERS_INTERLOCK_RED_SLOPE = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_RED_SLOPE);
		PAVERS_INTERLOCK_RED_SLOPE_PRO = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_RED_SLOPE_PRO);
		PAVERS_INTERLOCK_YELLOW = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_YELLOW);
		PAVERS_INTERLOCK_YELLOW_SLAB = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_YELLOW_SLAB);
		PAVERS_INTERLOCK_YELLOW_PLATE = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_YELLOW_PLATE);
		PAVERS_INTERLOCK_YELLOW_SLOPE = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_YELLOW_SLOPE);
		PAVERS_INTERLOCK_YELLOW_SLOPE_PRO = block(NcbRoadblckModBlocks.PAVERS_INTERLOCK_YELLOW_SLOPE_PRO);
		PAVERS_SQUARE_GRAY = block(NcbRoadblckModBlocks.PAVERS_SQUARE_GRAY);
		PAVERS_SQUARE_GRAY_SLAB = block(NcbRoadblckModBlocks.PAVERS_SQUARE_GRAY_SLAB);
		PAVERS_SQUARE_GRAY_PLATE = block(NcbRoadblckModBlocks.PAVERS_SQUARE_GRAY_PLATE);
		PAVERS_SQUARE_GRAY_SLOPE = block(NcbRoadblckModBlocks.PAVERS_SQUARE_GRAY_SLOPE);
		PAVERS_SQUARE_GRAY_SLOPE_PRO = block(NcbRoadblckModBlocks.PAVERS_SQUARE_GRAY_SLOPE_PRO);
		PAVERS_SQUARE_GREEN = block(NcbRoadblckModBlocks.PAVERS_SQUARE_GREEN);
		PAVERS_SQUARE_GREEN_SLAB = block(NcbRoadblckModBlocks.PAVERS_SQUARE_GREEN_SLAB);
		PAVERS_SQUARE_GREEN_PLATE = block(NcbRoadblckModBlocks.PAVERS_SQUARE_GREEN_PLATE);
		PAVERS_SQUARE_GREEN_SLOPE = block(NcbRoadblckModBlocks.PAVERS_SQUARE_GREEN_SLOPE);
		PAVERS_SQUARE_GREEN_SLOPE_PRO = block(NcbRoadblckModBlocks.PAVERS_SQUARE_GREEN_SLOPE_PRO);
		PAVERS_SQUARE_RED = block(NcbRoadblckModBlocks.PAVERS_SQUARE_RED);
		PAVERS_SQUARE_RED_SLAB = block(NcbRoadblckModBlocks.PAVERS_SQUARE_RED_SLAB);
		PAVERS_SQUARE_RED_PLATE = block(NcbRoadblckModBlocks.PAVERS_SQUARE_RED_PLATE);
		PAVERS_SQUARE_RED_SLOPE = block(NcbRoadblckModBlocks.PAVERS_SQUARE_RED_SLOPE);
		PAVERS_SQUARE_RED_SLOPE_PRO = block(NcbRoadblckModBlocks.PAVERS_SQUARE_RED_SLOPE_PRO);
		PAVERS_SQUARE_YELLOW = block(NcbRoadblckModBlocks.PAVERS_SQUARE_YELLOW);
		PAVERS_SQUARE_YELLOW_SLAB = block(NcbRoadblckModBlocks.PAVERS_SQUARE_YELLOW_SLAB);
		PAVERS_SQUARE_YELLOW_PLATE = block(NcbRoadblckModBlocks.PAVERS_SQUARE_YELLOW_PLATE);
		PAVERS_SQUARE_YELLOW_SLOPE = block(NcbRoadblckModBlocks.PAVERS_SQUARE_YELLOW_SLOPE);
		PAVERS_SQUARE_YELLOW_SLOPE_PRO = block(NcbRoadblckModBlocks.PAVERS_SQUARE_YELLOW_SLOPE_PRO);
		ASPHALT_TIDELINE = block(NcbRoadblckModBlocks.ASPHALT_TIDELINE);
		ASPHALT_TIDELINE_SLAB = block(NcbRoadblckModBlocks.ASPHALT_TIDELINE_SLAB);
		ASPHALT_TIDELINE_L_SLAB = block(NcbRoadblckModBlocks.ASPHALT_TIDELINE_L_SLAB);
		ASPHALT_TIDELINE_R_SLAB = block(NcbRoadblckModBlocks.ASPHALT_TIDELINE_R_SLAB);
		ASPHALT_TIDELINE_L = block(NcbRoadblckModBlocks.ASPHALT_TIDELINE_L);
		ASPHALT_TIDELINE_R = block(NcbRoadblckModBlocks.ASPHALT_TIDELINE_R);
		ASPHALT_WHITE_WIDELINE = block(NcbRoadblckModBlocks.ASPHALT_WHITE_WIDELINE);
		ASPHALT_WHITE_WIDELINE_SLAB = block(NcbRoadblckModBlocks.ASPHALT_WHITE_WIDELINE_SLAB);
		ASPHALT_SOLID_AND_DOTTED_LINE = block(NcbRoadblckModBlocks.ASPHALT_SOLID_AND_DOTTED_LINE);
		ASPHALT_SOLID_AND_DOTTED_LINE_SLAB = block(NcbRoadblckModBlocks.ASPHALT_SOLID_AND_DOTTED_LINE_SLAB);
		ASPHALT_YIELD_LINE = block(NcbRoadblckModBlocks.ASPHALT_YIELD_LINE);
		ASPHALT_YIELD_LINE_SLAB = block(NcbRoadblckModBlocks.ASPHALT_YIELD_LINE_SLAB);
		SHOULDER_ASPHALT = block(NcbRoadblckModBlocks.SHOULDER_ASPHALT);
		SHOULDER_ASPHALT_SLAB = block(NcbRoadblckModBlocks.SHOULDER_ASPHALT_SLAB);
		SHOULDER_MARBLE = block(NcbRoadblckModBlocks.SHOULDER_MARBLE);
		SHOULDER_MARBLE_SLAB = block(NcbRoadblckModBlocks.SHOULDER_MARBLE_SLAB);
		MARBLE = block(NcbRoadblckModBlocks.MARBLE);
		MARBLE_SLAB = block(NcbRoadblckModBlocks.MARBLE_SLAB);
		CEMENT = block(NcbRoadblckModBlocks.CEMENT);
		CEMENT_SLAB = block(NcbRoadblckModBlocks.CEMENT_SLAB);
		PATTERN_STEEL = block(NcbRoadblckModBlocks.PATTERN_STEEL);
		PATTERN_STEEL_SLAB = block(NcbRoadblckModBlocks.PATTERN_STEEL_SLAB);
		SHOULDER_ASPHALT_L_SLOPE = block(NcbRoadblckModBlocks.SHOULDER_ASPHALT_L_SLOPE);
		SHOULDER_ASPHALT_R_SLOPE = block(NcbRoadblckModBlocks.SHOULDER_ASPHALT_R_SLOPE);
		SHOULDER_ASPHALT_L_SLOPE_PRO = block(NcbRoadblckModBlocks.SHOULDER_ASPHALT_L_SLOPE_PRO);
		SHOULDER_ASPHALT_R_SLOPE_PRO = block(NcbRoadblckModBlocks.SHOULDER_ASPHALT_R_SLOPE_PRO);
		SHOULDER_MARBLE_L_SLOPE = block(NcbRoadblckModBlocks.SHOULDER_MARBLE_L_SLOPE);
		SHOULDER_MARBLE_R_SLOPE = block(NcbRoadblckModBlocks.SHOULDER_MARBLE_R_SLOPE);
		SHOULDER_MARBLE_L_SLOPE_PRO = block(NcbRoadblckModBlocks.SHOULDER_MARBLE_L_SLOPE_PRO);
		SHOULDER_MARBLE_R_SLOPE_PRO = block(NcbRoadblckModBlocks.SHOULDER_MARBLE_R_SLOPE_PRO);
		SHOULDER_ASPHALT_SLASH = block(NcbRoadblckModBlocks.SHOULDER_ASPHALT_SLASH);
		SHOULDER_ASPHALT_SLASH_SLAB = block(NcbRoadblckModBlocks.SHOULDER_ASPHALT_SLASH_SLAB);
		SHOULDER_MARBLE_SLASH = block(NcbRoadblckModBlocks.SHOULDER_MARBLE_SLASH);
		SHOULDER_MARBLE_SLASH_SLAB = block(NcbRoadblckModBlocks.SHOULDER_MARBLE_SLASH_SLAB);
		SHOULDER_RAINGRATE = block(NcbRoadblckModBlocks.SHOULDER_RAINGRATE);
		SHOULDER_RAINGRATE_SLAB = block(NcbRoadblckModBlocks.SHOULDER_RAINGRATE_SLAB);
		ELECTRIC_WRENCH = REGISTRY.register("electric_wrench", ElectricWrenchItem::new);
		BOLLARD_SIDEWALK = block(NcbRoadblckModBlocks.BOLLARD_SIDEWALK);
		STONE_PILLAR = block(NcbRoadblckModBlocks.STONE_PILLAR);
		SPEED_BUMP = block(NcbRoadblckModBlocks.SPEED_BUMP);
		GUARDRAIL = block(NcbRoadblckModBlocks.GUARDRAIL);
		GUARDRAIL_SMALL = block(NcbRoadblckModBlocks.GUARDRAIL_SMALL);
		MARKING_LEFT = block(NcbRoadblckModBlocks.MARKING_LEFT);
		MARKING_LEFT_RIGHT = block(NcbRoadblckModBlocks.MARKING_LEFT_RIGHT);
		MARKING_LEFT_UTURN = block(NcbRoadblckModBlocks.MARKING_LEFT_UTURN);
		MARKING_OFFSET_LEFT = block(NcbRoadblckModBlocks.MARKING_OFFSET_LEFT);
		MARKING_OFFSET_RIGHT = block(NcbRoadblckModBlocks.MARKING_OFFSET_RIGHT);
		MARKING_RIGHT = block(NcbRoadblckModBlocks.MARKING_RIGHT);
		MARKING_STRAIGHT = block(NcbRoadblckModBlocks.MARKING_STRAIGHT);
		MARKING_STRAIGHT_LEFT = block(NcbRoadblckModBlocks.MARKING_STRAIGHT_LEFT);
		MARKING_STRAIGHT_RIGHT = block(NcbRoadblckModBlocks.MARKING_STRAIGHT_RIGHT);
		MARKING_STRAIGHT_UTURN = block(NcbRoadblckModBlocks.MARKING_STRAIGHT_UTURN);
		MARKING_UTURN = block(NcbRoadblckModBlocks.MARKING_UTURN);
		SUNGLASSES = REGISTRY.register("sunglasses", SunglassesItem::new);
		BLIND_PATH_BAR = block(NcbRoadblckModBlocks.BLIND_PATH_BAR);
		BLIND_PATH_BAR_SLAB = block(NcbRoadblckModBlocks.BLIND_PATH_BAR_SLAB);
		BLIND_PATH_DOT = block(NcbRoadblckModBlocks.BLIND_PATH_DOT);
		BLIND_PATH_DOT_SLAB = block(NcbRoadblckModBlocks.BLIND_PATH_DOT_SLAB);
		BLIND_PATH_BAR_SLOPE = block(NcbRoadblckModBlocks.BLIND_PATH_BAR_SLOPE);
		BLIND_PATH_BAR_SLOPE_PRO = block(NcbRoadblckModBlocks.BLIND_PATH_BAR_SLOPE_PRO);
		BLIND_PATH_DOT_SLOPE = block(NcbRoadblckModBlocks.BLIND_PATH_DOT_SLOPE);
		BLIND_PATH_DOT_SLOPE_PRO = block(NcbRoadblckModBlocks.BLIND_PATH_DOT_SLOPE_PRO);
		MARKING_WATCH_FOR_PEDESTRIANS = block(NcbRoadblckModBlocks.MARKING_WATCH_FOR_PEDESTRIANS);
		MARKING_60_LOWSPEED = block(NcbRoadblckModBlocks.MARKING_60_LOWSPEED);
		MARKING_80_LOWSPEED = block(NcbRoadblckModBlocks.MARKING_80_LOWSPEED);
		MARKING_100_LOWSPEED = block(NcbRoadblckModBlocks.MARKING_100_LOWSPEED);
		MARKING_40_LOWSPEED = block(NcbRoadblckModBlocks.MARKING_40_LOWSPEED);
		MARKING_60_HIGHSPEED = block(NcbRoadblckModBlocks.MARKING_60_HIGHSPEED);
		MARKING_80_HIGHSPEED = block(NcbRoadblckModBlocks.MARKING_80_HIGHSPEED);
		MARKING_100_HIGHSPEED = block(NcbRoadblckModBlocks.MARKING_100_HIGHSPEED);
		MARKING_120_HIGHSPEED = block(NcbRoadblckModBlocks.MARKING_120_HIGHSPEED);
		TRAFFIC_SIGNAL_POLE = block(NcbRoadblckModBlocks.TRAFFIC_SIGNAL_POLE);
		TRAFFIC_SIGNAL_MAST = block(NcbRoadblckModBlocks.TRAFFIC_SIGNAL_MAST);
		ROADSIGN_STOP = block(NcbRoadblckModBlocks.ROADSIGN_STOP);
		TRAFFIC_SIGNAL_SMALLPOLE = block(NcbRoadblckModBlocks.TRAFFIC_SIGNAL_SMALLPOLE);
		ROADSIGN_YIELD = block(NcbRoadblckModBlocks.ROADSIGN_YIELD);
		ROADSIGN_CROSSROADS = block(NcbRoadblckModBlocks.ROADSIGN_CROSSROADS);
		ROADSIGN_JUNCTION_LEFT = block(NcbRoadblckModBlocks.ROADSIGN_JUNCTION_LEFT);
		ROADSIGN_JUNCTION_RIGHT = block(NcbRoadblckModBlocks.ROADSIGN_JUNCTION_RIGHT);
		ROADSIGN_JOINING_LEFT = block(NcbRoadblckModBlocks.ROADSIGN_JOINING_LEFT);
		ROADSIGN_JOINING_RIGHT = block(NcbRoadblckModBlocks.ROADSIGN_JOINING_RIGHT);
		ROADSIGN_DIVERGING_LEFT = block(NcbRoadblckModBlocks.ROADSIGN_DIVERGING_LEFT);
		ROADSIGN_DIVERGING_RIGHT = block(NcbRoadblckModBlocks.ROADSIGN_DIVERGING_RIGHT);
		ROADSIGN_ROUNDABOUT = block(NcbRoadblckModBlocks.ROADSIGN_ROUNDABOUT);
		ROADSIGN_TURN_LEFT = block(NcbRoadblckModBlocks.ROADSIGN_TURN_LEFT);
		ROADSIGN_TURN_RIGHT = block(NcbRoadblckModBlocks.ROADSIGN_TURN_RIGHT);
		ROADSIGN_REVERSE_CURVE_LEFT = block(NcbRoadblckModBlocks.ROADSIGN_REVERSE_CURVE_LEFT);
		ROADSIGN_REVERSE_CURVE_RIGHT = block(NcbRoadblckModBlocks.ROADSIGN_REVERSE_CURVE_RIGHT);
		ROADSIGN_WINDING_LEFT = block(NcbRoadblckModBlocks.ROADSIGN_WINDING_LEFT);
		ROADSIGN_WINDING_RIGHT = block(NcbRoadblckModBlocks.ROADSIGN_WINDING_RIGHT);
		ROADSIGN_STEEP_ASCENT = block(NcbRoadblckModBlocks.ROADSIGN_STEEP_ASCENT);
		ROADSIGN_STEEP_DESCENT = block(NcbRoadblckModBlocks.ROADSIGN_STEEP_DESCENT);
		ROADSIGN_CONTINUOUS_DESCENT = block(NcbRoadblckModBlocks.ROADSIGN_CONTINUOUS_DESCENT);
		ROADSIGN_NARROWS = block(NcbRoadblckModBlocks.ROADSIGN_NARROWS);
		ROADSIGN_NARROWS_LEFT = block(NcbRoadblckModBlocks.ROADSIGN_NARROWS_LEFT);
		ROADSIGN_NARROWS_RIGHT = block(NcbRoadblckModBlocks.ROADSIGN_NARROWS_RIGHT);
		ROADSIGN_NARROW_BRIDGE = block(NcbRoadblckModBlocks.ROADSIGN_NARROW_BRIDGE);
		ROADSIGN_TWOWAY_TRAFFIC = block(NcbRoadblckModBlocks.ROADSIGN_TWOWAY_TRAFFIC);
		ROADSIGN_PEDESTRIANS = block(NcbRoadblckModBlocks.ROADSIGN_PEDESTRIANS);
		ROADSIGN_CHILDREN = block(NcbRoadblckModBlocks.ROADSIGN_CHILDREN);
		ROADSIGN_DISABLED_PERSONS = block(NcbRoadblckModBlocks.ROADSIGN_DISABLED_PERSONS);
		ROADSIGN_NONMOTORIZED_VEHICLES = block(NcbRoadblckModBlocks.ROADSIGN_NONMOTORIZED_VEHICLES);
		ROADSIGN_TRAFFIC_SIGNALS = block(NcbRoadblckModBlocks.ROADSIGN_TRAFFIC_SIGNALS);
		ROADSIGN_FALLINGROCKS_LEFT = block(NcbRoadblckModBlocks.ROADSIGN_FALLINGROCKS_LEFT);
		ROADSIGN_FALLINGROCKS_RIGHT = block(NcbRoadblckModBlocks.ROADSIGN_FALLINGROCKS_RIGHT);
		ROADSIGN_MOUNTAIN_LEFT = block(NcbRoadblckModBlocks.ROADSIGN_MOUNTAIN_LEFT);
		ROADSIGN_MOUNTAIN_RIGHT = block(NcbRoadblckModBlocks.ROADSIGN_MOUNTAIN_RIGHT);
		ROADSIGN_VILLAGE = block(NcbRoadblckModBlocks.ROADSIGN_VILLAGE);
		ROADSIGN_TUNNEL = block(NcbRoadblckModBlocks.ROADSIGN_TUNNEL);
		ROADSIGN_DANGERS = block(NcbRoadblckModBlocks.ROADSIGN_DANGERS);
		ROADSIGN_WORKS = block(NcbRoadblckModBlocks.ROADSIGN_WORKS);
		ROADSIGN_Y_JUNCTION = block(NcbRoadblckModBlocks.ROADSIGN_Y_JUNCTION);
		ROADSIGN_T_JUNCTION = block(NcbRoadblckModBlocks.ROADSIGN_T_JUNCTION);
		ROADSIGN_NO_ENTRY = block(NcbRoadblckModBlocks.ROADSIGN_NO_ENTRY);
		ROADSIGN_NO_THOROUGHFARE = block(NcbRoadblckModBlocks.ROADSIGN_NO_THOROUGHFARE);
		ROADSIGN_NO_LEFT_TURN = block(NcbRoadblckModBlocks.ROADSIGN_NO_LEFT_TURN);
		ROADSIGN_NO_LEFT_OR_RIGHT_TURN = block(NcbRoadblckModBlocks.ROADSIGN_NO_LEFT_OR_RIGHT_TURN);
		ROADSIGN_NO_RIGHT_TURN = block(NcbRoadblckModBlocks.ROADSIGN_NO_RIGHT_TURN);
		ROADSIGN_NO_STRAIGHT_AHEAD_OR_LEFT_TURN = block(NcbRoadblckModBlocks.ROADSIGN_NO_STRAIGHT_AHEAD_OR_LEFT_TURN);
		ROADSIGN_NO_STRAIGHT_AHEAD = block(NcbRoadblckModBlocks.ROADSIGN_NO_STRAIGHT_AHEAD);
		ROADSIGN_NO_STRAIGHT_AHEAD_OR_RIGHT_TURN = block(NcbRoadblckModBlocks.ROADSIGN_NO_STRAIGHT_AHEAD_OR_RIGHT_TURN);
		ROADSIGN_NO_UTURN = block(NcbRoadblckModBlocks.ROADSIGN_NO_UTURN);
		ROADSIGN_NO_ENTRY_FOR_ARTICULATED_VEHICLES = block(NcbRoadblckModBlocks.ROADSIGN_NO_ENTRY_FOR_ARTICULATED_VEHICLES);
		ROADSIGN_NO_ENTRY_FOR_BUSES = block(NcbRoadblckModBlocks.ROADSIGN_NO_ENTRY_FOR_BUSES);
		ROADSIGN_NO_ENTRY_FOR_MOTOR_VEHICLES = block(NcbRoadblckModBlocks.ROADSIGN_NO_ENTRY_FOR_MOTOR_VEHICLES);
		ROADSIGN_NO_ENTRY_FOR_MOTORCYCLES = block(NcbRoadblckModBlocks.ROADSIGN_NO_ENTRY_FOR_MOTORCYCLES);
		ROADSIGN_NO_ENTRY_FOR_NON_MOTORIZED_VEHICLES = block(NcbRoadblckModBlocks.ROADSIGN_NO_ENTRY_FOR_NON_MOTORIZED_VEHICLES);
		ROADSIGN_NO_ENTRY_FOR_PASSENGER_CARS = block(NcbRoadblckModBlocks.ROADSIGN_NO_ENTRY_FOR_PASSENGER_CARS);
		ROADSIGN_NO_ENTRY_FOR_PEDESTRIANS = block(NcbRoadblckModBlocks.ROADSIGN_NO_ENTRY_FOR_PEDESTRIANS);
		ROADSIGN_NO_ENTRY_FOR_THREE_WHEELED_VEHICLES = block(NcbRoadblckModBlocks.ROADSIGN_NO_ENTRY_FOR_THREE_WHEELED_VEHICLES);
		ROADSIGN_NO_ENTRY_FOR_TRACTORS = block(NcbRoadblckModBlocks.ROADSIGN_NO_ENTRY_FOR_TRACTORS);
		ROADSIGN_NO_ENTRY_FOR_TRUCKS = block(NcbRoadblckModBlocks.ROADSIGN_NO_ENTRY_FOR_TRUCKS);
		ROADSIGN_NO_HONKING = block(NcbRoadblckModBlocks.ROADSIGN_NO_HONKING);
		ROADSIGN_STOP_FOR_INSPECTION = block(NcbRoadblckModBlocks.ROADSIGN_STOP_FOR_INSPECTION);
		ROADSIGN_SPEED_LIMIT_5 = block(NcbRoadblckModBlocks.ROADSIGN_SPEED_LIMIT_5);
		ROADSIGN_SPEED_LIMIT_10 = block(NcbRoadblckModBlocks.ROADSIGN_SPEED_LIMIT_10);
		ROADSIGN_SPEED_LIMIT_15 = block(NcbRoadblckModBlocks.ROADSIGN_SPEED_LIMIT_15);
		ROADSIGN_SPEED_LIMIT_30 = block(NcbRoadblckModBlocks.ROADSIGN_SPEED_LIMIT_30);
		ROADSIGN_SPEED_LIMIT_40 = block(NcbRoadblckModBlocks.ROADSIGN_SPEED_LIMIT_40);
		ROADSIGN_SPEED_LIMIT_60 = block(NcbRoadblckModBlocks.ROADSIGN_SPEED_LIMIT_60);
		ROADSIGN_SPEED_LIMIT_80 = block(NcbRoadblckModBlocks.ROADSIGN_SPEED_LIMIT_80);
		ROADSIGN_SPEED_LIMIT_100 = block(NcbRoadblckModBlocks.ROADSIGN_SPEED_LIMIT_100);
		ROADSIGN_SPEED_LIMIT_120 = block(NcbRoadblckModBlocks.ROADSIGN_SPEED_LIMIT_120);
		ROADSIGN_NO_OVERTAKING = block(NcbRoadblckModBlocks.ROADSIGN_NO_OVERTAKING);
		ROADSIGN_NO_PARKING = block(NcbRoadblckModBlocks.ROADSIGN_NO_PARKING);
		ROADSIGN_NO_WAITING = block(NcbRoadblckModBlocks.ROADSIGN_NO_WAITING);
		ROADSIGN_GIVE_WAY_TO_ONCOMING_VEHICLES = block(NcbRoadblckModBlocks.ROADSIGN_GIVE_WAY_TO_ONCOMING_VEHICLES);
		ROADSIGN_ONLY_TURN_LEFT = block(NcbRoadblckModBlocks.ROADSIGN_ONLY_TURN_LEFT);
		ROADSIGN_ONLY_TURN_LEFT_OR_RIGHT = block(NcbRoadblckModBlocks.ROADSIGN_ONLY_TURN_LEFT_OR_RIGHT);
		ROADSIGN_ONLY_STRAIGHT_AHEAD_OR_TURN_LEFT = block(NcbRoadblckModBlocks.ROADSIGN_ONLY_STRAIGHT_AHEAD_OR_TURN_LEFT);
		ROADSIGN_ONLY_STRAIGHT_AHEAD = block(NcbRoadblckModBlocks.ROADSIGN_ONLY_STRAIGHT_AHEAD);
		ROADSIGN_ONLY_STRAIGHT_AHEAD_OR_TURN_RIGHT = block(NcbRoadblckModBlocks.ROADSIGN_ONLY_STRAIGHT_AHEAD_OR_TURN_RIGHT);
		ROADSIGN_KEEP_LEFT = block(NcbRoadblckModBlocks.ROADSIGN_KEEP_LEFT);
		ROADSIGN_KEEP_RIGHT = block(NcbRoadblckModBlocks.ROADSIGN_KEEP_RIGHT);
		ROADSIGN_KEEP_ROUNDABOUT = block(NcbRoadblckModBlocks.ROADSIGN_KEEP_ROUNDABOUT);
		ROADSIGN_ONLY_MOTOR_VEHICLES = block(NcbRoadblckModBlocks.ROADSIGN_ONLY_MOTOR_VEHICLES);
		ROADSIGN_ONLY_NON_MOTORIZED_VEHICLES = block(NcbRoadblckModBlocks.ROADSIGN_ONLY_NON_MOTORIZED_VEHICLES);
		ROADSIGN_ONLY_PEDESTRIANS = block(NcbRoadblckModBlocks.ROADSIGN_ONLY_PEDESTRIANS);
		ROADSIGN_SOUND_HORN = block(NcbRoadblckModBlocks.ROADSIGN_SOUND_HORN);
		ROADSIGN_SWITCH_ON_LIGHTS = block(NcbRoadblckModBlocks.ROADSIGN_SWITCH_ON_LIGHTS);
		ROADSIGN_MINIMUM_SPEED_LIMIT_40 = block(NcbRoadblckModBlocks.ROADSIGN_MINIMUM_SPEED_LIMIT_40);
		ROADSIGN_MINIMUM_SPEED_LIMIT_60 = block(NcbRoadblckModBlocks.ROADSIGN_MINIMUM_SPEED_LIMIT_60);
		ROADSIGN_MINIMUM_SPEED_LIMIT_80 = block(NcbRoadblckModBlocks.ROADSIGN_MINIMUM_SPEED_LIMIT_80);
		ROADSIGN_MINIMUM_SPEED_LIMIT_100 = block(NcbRoadblckModBlocks.ROADSIGN_MINIMUM_SPEED_LIMIT_100);
		ROADSIGN_ONLY_TURN_RIGHT = block(NcbRoadblckModBlocks.ROADSIGN_ONLY_TURN_RIGHT);
		ROADSIGN_PARKING = block(NcbRoadblckModBlocks.ROADSIGN_PARKING);
		ROADSIGN_PARKING_LEFT = block(NcbRoadblckModBlocks.ROADSIGN_PARKING_LEFT);
		ROADSIGN_PARKING_RIGHT = block(NcbRoadblckModBlocks.ROADSIGN_PARKING_RIGHT);
		ROADSIGN_PARKING_RESERVED = block(NcbRoadblckModBlocks.ROADSIGN_PARKING_RESERVED);
		ROADSIGN_PARKING_FOR_BUSES = block(NcbRoadblckModBlocks.ROADSIGN_PARKING_FOR_BUSES);
		ROADSIGN_PARKING_FOR_SCHOOL_BUSES = block(NcbRoadblckModBlocks.ROADSIGN_PARKING_FOR_SCHOOL_BUSES);
		ROADSIGN_PARKING_FOR_TAXIS = block(NcbRoadblckModBlocks.ROADSIGN_PARKING_FOR_TAXIS);
		ROADSIGN_PARKING_FOR_EV_CHARGING = block(NcbRoadblckModBlocks.ROADSIGN_PARKING_FOR_EV_CHARGING);
		ROADSIGN_PARKING_FOR_NON_MOTORIZED_VEHICLES = block(NcbRoadblckModBlocks.ROADSIGN_PARKING_FOR_NON_MOTORIZED_VEHICLES);
		ROADSIGN_PARKING_FOR_DISABLED_PERSONS = block(NcbRoadblckModBlocks.ROADSIGN_PARKING_FOR_DISABLED_PERSONS);
		ROADSIGN_PEDESTRIAN_CROSSING = block(NcbRoadblckModBlocks.ROADSIGN_PEDESTRIAN_CROSSING);
		ROADSIGN_UTURN = block(NcbRoadblckModBlocks.ROADSIGN_UTURN);
		ROADSIGN_PRIORITY_OVER_ONCOMING_VEHICLES = block(NcbRoadblckModBlocks.ROADSIGN_PRIORITY_OVER_ONCOMING_VEHICLES);
		ROADSIGN_HARD_SHOULDER_AVAILABLE_FOR_TRAFFIC = block(NcbRoadblckModBlocks.ROADSIGN_HARD_SHOULDER_AVAILABLE_FOR_TRAFFIC);
		ROADSIGN_HARD_SHOULDER_AVAILABLE_END = block(NcbRoadblckModBlocks.ROADSIGN_HARD_SHOULDER_AVAILABLE_END);
		ROADSIGN_HARD_SHOULDER_AVAILABLE_CLOSE = block(NcbRoadblckModBlocks.ROADSIGN_HARD_SHOULDER_AVAILABLE_CLOSE);
		ROADSIGN_END_OF_NO_OVERTAKING = block(NcbRoadblckModBlocks.ROADSIGN_END_OF_NO_OVERTAKING);
		ROADSIGN_END_OF_SPEED_LIMIT_30 = block(NcbRoadblckModBlocks.ROADSIGN_END_OF_SPEED_LIMIT_30);
		ROADSIGN_END_OF_SPEED_LIMIT_40 = block(NcbRoadblckModBlocks.ROADSIGN_END_OF_SPEED_LIMIT_40);
		ROADSIGN_END_OF_SPEED_LIMIT_60 = block(NcbRoadblckModBlocks.ROADSIGN_END_OF_SPEED_LIMIT_60);
		ROADSIGN_END_OF_SPEED_LIMIT_80 = block(NcbRoadblckModBlocks.ROADSIGN_END_OF_SPEED_LIMIT_80);
		ROADSIGN_END_OF_SPEED_LIMIT_100 = block(NcbRoadblckModBlocks.ROADSIGN_END_OF_SPEED_LIMIT_100);
		MANHOLE_COVER = block(NcbRoadblckModBlocks.MANHOLE_COVER);
		CEMENT_HIGH_DENSITY = block(NcbRoadblckModBlocks.CEMENT_HIGH_DENSITY);
		CEMENT_HIGH_DENSITY_SLAB = block(NcbRoadblckModBlocks.CEMENT_HIGH_DENSITY_SLAB);
	}

	// Start of user code block custom items
	// End of user code block custom items
	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}
}